/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.loanapply.loanapply.action;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jcifs.smb.PictureUpload;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.LookupDispatchAction;
import org.xpup.common.exception.BusinessException;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.common.util.BusiConst;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysloan.common.loanconditionsset.ILoanConditionsParamSetBS;
import org.xpup.hafmis.sysloan.loanapply.loanapply.bsinterface.ILoanapplyBS;
import org.xpup.hafmis.sysloan.loanapply.loanapply.form.LoanapplyTdNewAF;

/**
 * MyEclipse Struts Creation date: 10-02-2007 XDoclet definition:
 * 
 * @struts.action path="loanapplytdmaintianAC" name="loanapplytdnewAF"
 *                scope="request" validate="true"
 */
public class LoanapplyTdMainTianAC extends LookupDispatchAction {

  protected Map getKeyMethodMap() {
    Map map = new HashMap();
    map.put("button.sure", "sure");
    map.put("button.scan", "scan");
    map.put("button.delete", "delete");
    return map;
  }

  public ActionForward sure(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {

    LoanapplyTdNewAF loanapplytdnewAF = (LoanapplyTdNewAF) form;
    ActionMessages messages = null;
    ILoanapplyBS loanapplyBS = (ILoanapplyBS) BSUtils.getBusinessService(
        "loanapplyBS", this, mapping.getModuleConfig());
    ILoanConditionsParamSetBS loanConditionsParamSetBS = (ILoanConditionsParamSetBS) BSUtils
        .getBusinessService("loanConditionsParamSetBS", this, mapping
            .getModuleConfig());
    SecurityInfo securityInfo = (SecurityInfo) request.getSession()
        .getAttribute("SecurityInfo");

    try {
      // 把页面输入的年份转化成月
      int loanMonth = Integer.parseInt(loanapplytdnewAF.getLoantimeLimit()) * 12;
      loanapplytdnewAF.setLoantimeLimit(loanMonth + "");
      // BigDecimal money=
      // loanConditionsParamSetBS.canSysLoanMoney(loanapplytdnewAF,securityInfo);
      int loanMonthLimit = loanConditionsParamSetBS.canSysLoanlimit(
          loanapplytdnewAF, securityInfo);
      BigDecimal loanMoneyLimit = loanConditionsParamSetBS.canSysLoanlimit_1(
          loanapplytdnewAF, securityInfo);
      System.out.println("最大贷款年限===>" + loanMonthLimit);
      System.out.println("最大贷款金额===>" + loanMoneyLimit);
      loanapplytdnewAF.setLoanMonthLimit(loanMonthLimit);
      loanapplytdnewAF.setLoanMoneyLimit(loanMoneyLimit);
      loanapplyBS.saveBorrowerLoanInfo(loanapplytdnewAF, securityInfo);
      messages = new ActionMessages();
      messages.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage("信息已保存",
          false));
      saveErrors(request, messages);
    } catch (BusinessException e) {
      messages = new ActionMessages();
      messages.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(e
          .getLocalizedMessage().toString(), false));
      saveErrors(request, messages);
    }

    return mapping.findForward("loanapplytdshowAC");
  }

  public ActionForward scan(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response)
      throws Exception {
    ActionMessages messages = null;
    PictureUpload pu = new PictureUpload();
    String path;
    try {
      SecurityInfo securityInfo = (SecurityInfo) request.getSession()
          .getAttribute("SecurityInfo");
      String serverPath = BusiConst.UPLOAD_SERVER_PATH;
      path = pu.upload(securityInfo.getUserInfo().getUserIp(), "picture",
          serverPath);
      pu.delete(securityInfo.getUserInfo().getUserIp(), "picture");
      ILoanapplyBS loanapplyBS = (ILoanapplyBS) BSUtils.getBusinessService(
          "loanapplyBS", this, mapping.getModuleConfig());
      LoanapplyTdNewAF loanapplytdnewAF = (LoanapplyTdNewAF) form;
      loanapplyBS
          .updateBorrowerLoanInfo(loanapplytdnewAF.getContractId(), path); // 更新pl115
      messages = new ActionMessages();
      messages.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage("扫描完成",
          false));
      saveErrors(request, messages);
    } catch (BusinessException e) {
      messages = new ActionMessages();
      messages.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(e
          .getLocalizedMessage().toString(), false));
      saveErrors(request, messages);
    }

    return mapping.findForward("loanapplytdshowAC");
  }

  public ActionForward delete(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {
    LoanapplyTdNewAF loanapplytdnewAF = (LoanapplyTdNewAF) form;

    ILoanapplyBS loanapplyBS = (ILoanapplyBS) BSUtils.getBusinessService(
        "loanapplyBS", this, mapping.getModuleConfig());
    SecurityInfo securityInfo = (SecurityInfo) request.getSession()
        .getAttribute("SecurityInfo");
    ActionMessages messages = null;
    try {
      loanapplyBS.deletedBorrowerLoanInfo(loanapplytdnewAF.getContractId(),
          securityInfo);
    } catch (BusinessException e) {
      messages = new ActionMessages();
      messages.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(e
          .getLocalizedMessage().toString(), false));
      saveErrors(request, messages);
    } catch (Exception e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }

    return mapping.findForward("loanapplytdshowAC");
  }
}