/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.loanapply.loanapply.action;

import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.sysloan.dataready.develop.dto.HouseAddListDTO;
import org.xpup.hafmis.sysloan.loanapply.loanapply.bsinterface.ILoanapplyBS;

/** 
 * @author wangshuang
 * 根据所选楼盘号查询楼层次屋号下拉
 */
public class LoanapplyTcFindHouseAddAAC extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    try{
      response.setContentType("text/xml; charset=utf-8");
      PrintWriter out = response.getWriter();
      out.println("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
      out.println("<options>");
      String floorId = request.getParameter("floorId");
      ILoanapplyBS loanapplyBS = (ILoanapplyBS) BSUtils.getBusinessService(
          "loanapplyBS", this, mapping.getModuleConfig());
      //wshuang修改
      if(!floorId.equals("")&&!floorId.equals("all")){
        List list = loanapplyBS.findHouseAddListByFloorId(floorId);
        for(int i=0;i<list.size();i++){
          HouseAddListDTO dto = (HouseAddListDTO)list.get(i);
          out.println("<value>" + dto.getBuildId() + "</value>");
          out.println("<text>" + dto.getBuildNum()+dto.getBuildAdd() + "</text>");
        }
      }
      out.println("</options>");

      out.flush();
      out.close();

     }catch(Exception e){
       e.printStackTrace();
     }
      return null;
    }
}