/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.loanapply.loanapply.action;

import java.io.IOException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.hafmis.sysloan.loanapply.loanapply.dto.BankListDTO;

/**
 * MyEclipse Struts Creation date: 10-05-2007 XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class LoanapplyTcFindBankAAC extends Action {

  public ActionForward execute(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {

    response.setContentType("text/html;charset=UTF-8");
    response.setHeader("Cache-Control", "no-cache");

    String developerPaybank = (String) request.getParameter("developerPaybank");
    List list = (List) request.getSession().getAttribute("sessonbankOList");
    String bankName = "";
    if (developerPaybank.equals("") || developerPaybank == null) {
      bankName="";
    } else {
      for (int i = 0; i < list.size(); i++) {
        BankListDTO bDto = (BankListDTO) list.get(i);
        if (developerPaybank.equals(bDto.getBankKey())) {
          bankName = bDto.getBankValue();
        }
      }
    }

    String text = "";
    text = "dispplayAcc('" + bankName + "','" + developerPaybank + "');";
    try {
      response.getWriter().write(text);
    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    try {
      response.getWriter().close();
    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    return null;
  }
}