/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.loanbusiquery.loancontractquery.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.exception.BusinessException;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.common.util.BusiConst;
import org.xpup.hafmis.common.util.BusiTools;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysloan.loanapply.loanapply.bsinterface.ILoanapplyBS;
import org.xpup.hafmis.sysloan.loanapply.loanapply.form.LoanapplyTdNewAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-16-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class LoancontractqueryTdShowAC extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
	
    LoanapplyTdNewAF loanapplytdnewAF=new LoanapplyTdNewAF();

    ILoanapplyBS loanapplyBS = (ILoanapplyBS) BSUtils.getBusinessService("loanapplyBS", this, mapping.getModuleConfig());

    String contractid = (String) request.getSession().getAttribute("contractIdWY");
    SecurityInfo securityInfo = (SecurityInfo) request.getSession().getAttribute("SecurityInfo");
    
    if(contractid!=null){
      try {
        loanapplytdnewAF =loanapplyBS.showBorrowerLoanInfoByContractid(contractid,securityInfo);
        String mood=loanapplytdnewAF.getLoanMood();
        if(mood!=null){
          try {
            mood= BusiTools.getBusiValue(Integer.parseInt(mood), BusiConst.PLRECOVERTYPE);
          } catch (NumberFormatException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
          } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
          }
        }
        loanapplytdnewAF.setLoanMood(mood);
      } catch (BusinessException e) {
        e.printStackTrace();
      }
    }
    request.setAttribute("loanapplytdnewAF",loanapplytdnewAF);
    return mapping.findForward("loancontractquery_td_cell");
	}
}