/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.loanbusiquery.loancontractquery.action;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.Pagination;
import org.xpup.hafmis.sysloan.querystatistics.loanbusiquery.loancontractquery.form.LoanContractQueryAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2007
 * 
 * XDoclet definition:
 * @struts.action path="/loancontractqueryfindAC" name="loancontractqueryAF" scope="request" validate="true"
 */
public class LoancontractqueryFindAC extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoanContractQueryAF loancontractqueryAF = (LoanContractQueryAF) form;
    HashMap criterions = makeCriterionsMap(loancontractqueryAF);
    request.getSession().setAttribute("url", "find");
    Pagination pagination = new Pagination(0, 10, 1, "p10.contract_id", "DESC",criterions);
    String paginationKey = LoancontractqueryShowAC.PAGINATION_KEY;
    request.getSession().setAttribute(paginationKey, pagination);
    return mapping.findForward("loancontractqueryshowAC");
	}

  protected HashMap makeCriterionsMap(LoanContractQueryAF loancontractqueryAF) {
    HashMap map = new HashMap();
    String contactid =loancontractqueryAF.getContactid();
    if (!( contactid== null || "".equals(contactid.trim()))) {
      map.put("contactid", contactid);
    }
    String  borrowername= loancontractqueryAF.getBorrowername();
    if (!( borrowername== null || "".equals(borrowername.trim()))) {
      map.put("borrowername",borrowername );
    }
    String empid = loancontractqueryAF.getEmpid().trim();
    if (!( empid== null || "".equals(empid.trim()))) {
      map.put("empid",empid);
    }
    String  cardnum= loancontractqueryAF.getCardnum();
    if (!( cardnum== null || "".equals(cardnum.trim()))) {
      map.put("cardnum", cardnum);
    }
    String  consortname= loancontractqueryAF.getConsortname();;
    if (!( consortname== null || "".equals(consortname.trim()))) {
      map.put("consortname", consortname);
    }
    String  consortcardnum= loancontractqueryAF.getConsortcardnum();
    if (!( consortcardnum== null || "".equals(consortcardnum.trim()))) {
      map.put("consortcardnum", consortcardnum);
    }
    String  consortempid= loancontractqueryAF.getConsortempid();
    if (!( consortempid== null || "".equals(consortempid.trim()))) {
      map.put("consortempid", consortempid);
    }
    String  housetype= loancontractqueryAF.getHousetype();
    if (!( housetype== null || "".equals(housetype.trim()))) {
      map.put("housetype", housetype);
    }
    String  contact_st= loancontractqueryAF.getContact_st();
    if (!(contact_st == null || "".equals(contact_st.trim()))) {
      map.put("contact_st", contact_st);
    }
    String office = loancontractqueryAF.getOffice();
    if (!(office == null || "".equals(office.trim()))) {
      map.put("office", office);
    }
    String loanbank = loancontractqueryAF.getLoanbank();
    if (!( loanbank== null || "".equals(loanbank.trim()))) {
      map.put("loanbank", loanbank);
    }
    String  assistantorgid= loancontractqueryAF.getAssistantorgid();
    if (!( assistantorgid== null || "".equals(assistantorgid.trim()))) {
      map.put("assistantorgid",assistantorgid );
    }
    String  headid= loancontractqueryAF.getBuyhouseorgid();
    if (!( headid== null || "".equals(headid.trim()))) {
      map.put("headid", headid);
    }
    String  floorid= loancontractqueryAF.getFloorid();
    if (!( floorid == null || "".equals(floorid.trim()))) {
      map.put("floorid", floorid);
    }
    String floorName = loancontractqueryAF.getFloorName();
    if (!( floorName == null || "".equals(floorName.trim()))) {
      map.put("floorName", floorName);
    }
    String houseAreaSt = loancontractqueryAF.getHouseAreaSt();
    if (!( houseAreaSt == null || "".equals(houseAreaSt.trim()))) {
      map.put("houseAreaSt", houseAreaSt.trim());
    }
    String houseAreaEnd = loancontractqueryAF.getHouseAreaEnd();
    if (!( houseAreaEnd == null || "".equals(houseAreaEnd.trim()))) {
      map.put("houseAreaEnd", houseAreaEnd.trim());
    }
    String agreementDateSt = loancontractqueryAF.getAgreementDateSt();
    if (!( agreementDateSt == null || "".equals(agreementDateSt.trim()))) {
      map.put("agreementDateSt", agreementDateSt.trim());
    }
    String agreementDateEnd = loancontractqueryAF.getAgreementDateEnd();
    if (!( agreementDateEnd == null || "".equals(agreementDateEnd.trim()))) {
      map.put("agreementDateEnd", agreementDateEnd.trim());
    }
    String signAgreementDateStart = loancontractqueryAF.getSignAgreementDateStart();
    if (!( signAgreementDateStart == null || "".equals(signAgreementDateStart.trim()))) {
      map.put("signAgreementDateStart", signAgreementDateStart.trim());
    }
    String signAgreementDateEnd = loancontractqueryAF.getSignAgreementDateEnd();
    if (!( signAgreementDateEnd == null || "".equals(signAgreementDateEnd.trim()))) {
      map.put("signAgreementDateEnd", signAgreementDateEnd.trim());
    }
    String loanTimeLimitSt = loancontractqueryAF.getLoanTimeLimitSt();
    if (!( loanTimeLimitSt == null || "".equals(loanTimeLimitSt.trim()))) {
      map.put("loanTimeLimitSt", loanTimeLimitSt.trim());
    }
    String loanTimeLimitEnd = loancontractqueryAF.getLoanTimeLimitEnd();
    if (!( loanTimeLimitEnd == null || "".equals(loanTimeLimitEnd.trim()))) {
      map.put("loanTimeLimitEnd", loanTimeLimitEnd.trim());
    }
    String loanMoneySt = loancontractqueryAF.getLoanMoneySt();
    if (!( loanMoneySt == null || "".equals(loanMoneySt.trim()))) {
      map.put("loanMoneySt", loanMoneySt.trim());
    }
    String loanMoneyEnd = loancontractqueryAF.getLoanMoneyEnd();
    if (!( loanMoneyEnd == null || "".equals(loanMoneyEnd.trim()))) {
      map.put("loanMoneyEnd", loanMoneyEnd.trim());
    }
    String isSignAgreement = loancontractqueryAF.getIsSignAgreement();
    if (!( isSignAgreement == null || "".equals(isSignAgreement.trim()))) {
      map.put("isSignAgreement", isSignAgreement.trim());
    }
    String loanType = loancontractqueryAF.getLoanType();
    if (!( loanType == null || "".equals(loanType.trim()))) {
      map.put("loanType", loanType.trim());
    }
    String isRecoverClear = loancontractqueryAF.getIsRecoverClear();
    if (!( isRecoverClear == null || "".equals(isRecoverClear.trim()))) {
      map.put("isRecoverClear", isRecoverClear.trim());
    }
    String recoverClearDateSt = loancontractqueryAF.getRecoverClearDateSt();
    if (!( recoverClearDateSt == null || "".equals(recoverClearDateSt.trim()))) {
      map.put("recoverClearDateSt", recoverClearDateSt.trim());
    }
    String recoverClearDateEnd = loancontractqueryAF.getRecoverClearDateEnd();
    if (!( recoverClearDateEnd == null || "".equals(recoverClearDateEnd.trim()))) {
      map.put("recoverClearDateEnd", recoverClearDateEnd.trim());
    }
    return map;
  }
}
