/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.loanbusiquery.loancontractquery.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysloan.dataready.loanpara.bsinterface.ILoanDocNumDesignBS;
import org.xpup.hafmis.sysloan.loanapply.endorsecontract.form.EndorsecontractTcAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-16-2007
 * 
 * XDoclet definition:
 * @struts.action path="/loancontractqueryTgPrintAC" name="endorsecontractTcAF" scope="request" validate="true"
 */
public class LoancontractqueryTgPrintAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    EndorsecontractTcAF endorsecontractTcAF =(EndorsecontractTcAF)request.getSession().getAttribute("printtheEndorsecontractTcAF");
    
    
    
    String contractId =endorsecontractTcAF.getContractId();
    if(contractId==null){
      contractId ="";
    }
    endorsecontractTcAF.setContractId(contractId);
    String impawnContractId =endorsecontractTcAF.getImpawnContractId();
    if(impawnContractId==null){
      impawnContractId ="";
    }
    endorsecontractTcAF.setImpawnContractId(impawnContractId);
    String impawnPerson=endorsecontractTcAF.getImpawnPerson();
    if(impawnPerson==null){
      impawnPerson ="";
    }
    endorsecontractTcAF.setImpawnPerson(impawnPerson);
    String impawnMatterName=endorsecontractTcAF.getImpawnMatterName();
    if(impawnMatterName==null){
      impawnMatterName ="";
    }
    endorsecontractTcAF.setImpawnMatterName(impawnMatterName);
    String paperPersonName=endorsecontractTcAF.getPaperPersonName();
    if(paperPersonName==null){
      paperPersonName ="";
    }
    endorsecontractTcAF.setPaperPersonName(paperPersonName);
    String carNum=endorsecontractTcAF.getCarNum();
    if(carNum==null){
      carNum ="";
    }
    endorsecontractTcAF.setCarNum(carNum);
    String paperName =endorsecontractTcAF.getPaperName();
    if(paperName==null){
      paperName ="";
    }
    endorsecontractTcAF.setPaperName(paperName);
    String tel =endorsecontractTcAF.getTel();
    if(tel==null){
      tel ="";
    }
    endorsecontractTcAF.setTel(tel);
    String debitter =endorsecontractTcAF.getDebitter();
    if(debitter==null){
      debitter="";
    }
    endorsecontractTcAF.setDebitter(debitter);
    String assistantOrgName=endorsecontractTcAF.getAssistantOrgName();
    if(assistantOrgName==null){
      assistantOrgName ="";
    }
    endorsecontractTcAF.setAssistantOrgName(assistantOrgName);
    String office=endorsecontractTcAF.getOffice();
    if(office==null){
      office ="";
    }
    endorsecontractTcAF.setOffice(office);
    String impawnValue=endorsecontractTcAF.getImpawnValue();
    if(impawnValue==null){
      impawnValue ="";
    }
    endorsecontractTcAF.setImpawnValue(impawnValue);
    String cardKind =endorsecontractTcAF.getCardKind();
    if(cardKind==null){
      cardKind ="";
    }
    endorsecontractTcAF.setCardKind(cardKind);
    String  paperNum=endorsecontractTcAF.getPaperNum();
    if(paperNum==null){
      paperNum="";
    }
    endorsecontractTcAF.setPaperNum(paperNum);
    
    String mobile =endorsecontractTcAF.getMobile();
    
    if(mobile==null){
      mobile ="";
    }
    endorsecontractTcAF.setMobile(mobile);
    
    
    
    SecurityInfo securityInfo = (SecurityInfo) request.getSession().getAttribute("SecurityInfo");
    String opertname = securityInfo.getRealName();
    ILoanDocNumDesignBS loanDocNumDesignBS = (ILoanDocNumDesignBS) BSUtils
    .getBusinessService("sysloanloanDocNumDesignBS", this, mapping.getModuleConfig());
    String userName="";
    try {
      String name = loanDocNumDesignBS.getNamePara();

      if (name.equals("1")) {
        userName = securityInfo.getUserName();
      } else {
        userName = securityInfo.getRealName();
      }

    } catch (Exception e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    String time = securityInfo.getUserInfo().getPlbizDate();
    request.setAttribute("opertname", userName);
    request.setAttribute("time", time);
    request.setAttribute("endorsecontractTcAF", endorsecontractTcAF);
    request.getSession().setAttribute("printtheEndorsecontractTcAF", null);
    return mapping.findForward("loancontractquery_tg_print_cell");
	}
}