/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.loanbusiquery.loancontractquery.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysloan.dataready.loanpara.bsinterface.ILoanDocNumDesignBS;
import org.xpup.hafmis.sysloan.loanapply.loanapply.form.LoanapplyTcNewAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-16-2007
 * 
 * XDoclet definition:
 * @struts.action path="/loancontractqueryTcPrintAC" name="loanapplytcnewAF" scope="request" validate="true"
 */
public class LoancontractqueryTcPrintAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoanapplyTcNewAF loanapplytcnewAF = (LoanapplyTcNewAF) form;
    String housetype=loanapplytcnewAF.getHouseTypehidden();
    SecurityInfo securityInfo = (SecurityInfo) request.getSession()
    .getAttribute("SecurityInfo");
    //String opertname = securityInfo.getRealName();
    String time = securityInfo.getUserInfo().getPlbizDate();
   
    ILoanDocNumDesignBS loanDocNumDesignBS = (ILoanDocNumDesignBS) BSUtils
    .getBusinessService("sysloanloanDocNumDesignBS", this, mapping.getModuleConfig());
    String userName="";
    try {
      String name = loanDocNumDesignBS.getNamePara();

      if (name.equals("1")) {
        userName = securityInfo.getUserName();
      } else {
        userName = securityInfo.getRealName();
      }

    } catch (Exception e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    request.setAttribute("opertname", userName);
    request.setAttribute("time", time);
    request.setAttribute("loanapplytcnewAF", loanapplytcnewAF);
    if(housetype.equals("01")){ 
      if(loanapplytcnewAF.getBuyHouseContractId()==null){
        loanapplytcnewAF.setBuyHouseContractId("");
      }
      return mapping.findForward("loancontractquery_tcs_print_cell");
    }
		return mapping.findForward("loancontractquery_tce_print_cell");
	}
}