/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.chgbiz.chgperson.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.syscollection.chgbiz.chgperson.bsinterface.IChgpersonDoBS;

/**
 * MyEclipse Struts Creation date: 05-28-2008 XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class ChgpersonAAC extends Action {

  public ActionForward execute(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {
    response.setContentType("text/html;charset=UTF-8");
    response.setHeader("Cache-Control", "no-cache");
    String flag = "";
    String message = "系统中已经存在姓名和身份证号相同的职工,是否继续添加!";
    try {
      String orgId = request.getParameter("orgId");
      String empName = request.getParameter("empName");
      String cardNum = request.getParameter("cardNum");
      IChgpersonDoBS chgpersonDoBS = (IChgpersonDoBS) BSUtils
          .getBusinessService("chgpersonDoBS", this, mapping.getModuleConfig());
      int count = chgpersonDoBS.isExistSameEmpInfo(orgId, empName, cardNum);
      System.out.println(count+"=======>");
      if(count > 0){
        flag = "exist";
      }
      String text = "";
      text = "display_bit('" + flag + "','" + message + "')";
      response.getWriter().write(text);
      response.getWriter().close();
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
  }

}