/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysfinance.accmng.subjectbalance.action;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.Pagination;
import org.xpup.hafmis.sysfinance.accmng.listacc.form.ListaccAF;
import org.xpup.hafmis.sysfinance.accmng.subjectbalance.form.SubjectbalanceAF;

public class SubjcetbalanceFindAC extends Action {

  public ActionForward execute(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {
    try {
      SubjectbalanceAF f = (SubjectbalanceAF) form;
      HashMap criterions = makeCriterionsMap(f);
      Pagination pagination = new Pagination(0, 10, 1, "", "DESC", criterions);
      String paginationKey = getPaginationKey();
      request.getSession().setAttribute(paginationKey, pagination);
      f.reset(mapping, request);
      // 用来标识点击过查询按钮,用来在showAC中判断list的取法
      request.setAttribute("flag", "1");
    } catch (Exception e) {
      e.printStackTrace();
    }
    return mapping.findForward("subjectbalanceShowAC");
  }

  protected HashMap makeCriterionsMap(SubjectbalanceAF subjectbalanceAF) {
    HashMap m = new HashMap();
    String year = subjectbalanceAF.getCredenceDateYear().trim();
    m.put("year", year);
    String startMonth = subjectbalanceAF.getCredenceDateStartMonths().trim();
    m.put("startMonth", startMonth);
    String startSubjectCode = subjectbalanceAF.getSubjectCodeStart().trim();
    m.put("startSubjectCode", startSubjectCode);
    String endSubjectCode = subjectbalanceAF.getSubjectCodeEnd().trim();
    m.put("endSubjectCode", endSubjectCode);
    String subjectLevel = subjectbalanceAF.getSubjectLevel().trim();
    m.put("subjectLevel", subjectLevel);
    String office = subjectbalanceAF.getOfficeName().trim();
    m.put("office", office);
    return m;
  }

  protected String getPaginationKey() {
    return SubjectbalanceShowAC.PAGINATION_KEY;
  }
}