/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysfinance.accmng.subjectbalance.action;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.LookupDispatchAction;
import org.xpup.common.util.BSUtils;
import org.xpup.common.util.Pagination;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysfinance.accmng.subjectbalance.bsinterface.ISubjectbalanceBS;

/**
 * @Version : 1.0
 * @author : wangshuang
 * @struts.action validate="true"
 */
public class SubjectbalanceMaintainAC extends LookupDispatchAction {
  /*
   * Generated Methods
   */

  protected Map getKeyMethodMap() {
    HashMap map = new HashMap();
    map.put("button.print", "print");
    return map;
  }

  public ActionForward execute(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {

    try {
      ISubjectbalanceBS subjectbalanceBS = (ISubjectbalanceBS) BSUtils
          .getBusinessService("subjectbalanceBS", this, mapping
              .getModuleConfig());
      SecurityInfo securityInfo = (SecurityInfo) request.getSession()
          .getAttribute("SecurityInfo");
      String userName = "";
      String name = subjectbalanceBS.queryMakerPara();
      if (name.equals("1")) {
        userName = securityInfo.getUserName();
      } else {
        userName = securityInfo.getRealName();
      }
      Pagination pagination = (Pagination) request.getSession().getAttribute(
          SubjectbalanceShowAC.PAGINATION_KEY);
      String year = (String) pagination.getQueryCriterions().get("year");
      String month = (String) pagination.getQueryCriterions().get("startMonth");
      if (month.length() < 2) {
        month = "0" + month;
      }
      String countCredenceNum = subjectbalanceBS.queryCountCredenceNum(
          securityInfo.getBookId(), year + month);
      request.setAttribute("bizDate", year + "-" + month);
      request.setAttribute("countCredenceNum", countCredenceNum);
      request.setAttribute("userName", userName);
    } catch (Exception e) {
      e.printStackTrace();
    }
    return mapping.findForward("to_subjectbalance_cell");
  }
}