/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.contractchg.baseinfochg.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.sysloan.contractchg.baseinfochg.bsinterface.IBaseinfochgBS;
import org.xpup.hafmis.sysloan.loanapply.loanapply.form.LoanapplyTcNewAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-11-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class BaseinfochgTdShowAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    
    LoanapplyTcNewAF loanapplytcnewAF = new LoanapplyTcNewAF();   
    String contranctid=(String)request.getSession().getAttribute("contid");
    if(contranctid==null){//在AF里放个值，用来判断，如果没有合同编号页面为空，按钮全部禁用
      loanapplytcnewAF.setCoodm("15");
    }else{
    IBaseinfochgBS baseinfochgBS = (IBaseinfochgBS) BSUtils.getBusinessService("baseinfochgBS", this, mapping.getModuleConfig());
    try {
      loanapplytcnewAF=baseinfochgBS.showHouseInfo(contranctid);
    } catch (Exception e) {
      e.printStackTrace();
    }
    }
    String tcsetIsNeedDel=(String) request.getSession().getAttribute("tcsetIsNeedDel");
    loanapplytcnewAF.setIsNeedDel(tcsetIsNeedDel);
    request.getSession().setAttribute("tcsetIsNeedDel",null);
    request.setAttribute("loanapplytcnewAF",loanapplytcnewAF);
		return mapping.findForward("baseinfochgtd");
	}
}