/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.contractchg.baseinfochg.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.common.util.BusiConst;
import org.xpup.hafmis.common.util.BusiTools;
import org.xpup.hafmis.sysloan.contractchg.baseinfochg.bsinterface.IBaseinfochgBS;
import org.xpup.hafmis.sysloan.loanapply.loanapply.form.LoanapplyTbNewAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-14-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class BaseinfochgTcShowAC extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    IBaseinfochgBS baseinfochgBS = (IBaseinfochgBS) BSUtils.getBusinessService("baseinfochgBS", this, mapping.getModuleConfig());
    String maxauxiliaryid = (String) request.getAttribute("maxauxiliaryidchg");
    String sun = (String) request.getAttribute("sun");
    String temp_addtype = (String) request.getSession().getAttribute("temp_addtypechg");
    String contranctid=(String)request.getSession().getAttribute("contid");
    LoanapplyTbNewAF loanapplytbnewAF=new LoanapplyTbNewAF();
   
    if(contranctid==null){
      loanapplytbnewAF.setCoodm("15");//没有合同编号
    }else{
      try {
//        loanapplytbnewAF=baseinfochgBS.findAssistanBorrowerInfochg(contranctid,maxauxiliaryid);
        loanapplytbnewAF=baseinfochgBS.findAssistanBorrowerInfo_yg(contranctid,maxauxiliaryid,sun);
        if(temp_addtype!=null){
          LoanapplyTbNewAF laAF = new LoanapplyTbNewAF();
          laAF.setList(loanapplytbnewAF.getList());
          laAF.setContractId(loanapplytbnewAF.getContractId());
          laAF.setBorrowerName(loanapplytbnewAF.getBorrowerName());
          laAF.setTemp_tes("5");//说明点过添加，页面没有禁用，除了点击职工按钮后，部分禁用
          loanapplytbnewAF = laAF;
        }
        if(loanapplytbnewAF.getList().size()==0){
          loanapplytbnewAF.setCoodm("1");//有合同编号，没有辅助借款人页面除了合同编号和借款人姓名以外，没有只读的了
        }else{
          loanapplytbnewAF.setCoodm("2");//有合同编号和一个以上的辅助借款人，有一部分只读
        }
      } catch (Exception e) {
        e.printStackTrace();
      }
    }
    try {
      loanapplytbnewAF.setSexMap(BusiTools.listBusiProperty(BusiConst.SEX));
    } catch (Exception e) {
      e.printStackTrace();
    }
    try {
      loanapplytbnewAF.setCardkingMap(BusiTools
          .listBusiProperty(BusiConst.DOCUMENTSSTATE));
      loanapplytbnewAF.setRelationMap(BusiTools.listBusiProperty(BusiConst.RELATION));
    } catch (Exception e) {
      e.printStackTrace();
    } 
    String tbsetIsNeedDel=(String)request.getSession().getAttribute("tbsetIsNeedDel");
    loanapplytbnewAF.setIsNeedDel(tbsetIsNeedDel);//如果==1，说明要删除客户端的图片
    request.getSession().setAttribute("tbsetIsNeedDel",null);
    loanapplytbnewAF.setCount(loanapplytbnewAF.getList().size()+"");
    request.setAttribute("loanapplytbnewAF", loanapplytbnewAF);
		return mapping.findForward("baseinfochgtc");
	}
}