/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.contractchg.baseinfochg.action;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.common.util.Pagination;
import org.xpup.common.util.PaginationUtils;
import org.xpup.hafmis.common.util.BusiConst;
import org.xpup.hafmis.common.util.BusiTools;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysloan.contractchg.baseinfochg.bsinterface.IBaseinfochgBS;
import org.xpup.hafmis.sysloan.loanapply.loanapply.form.LoanapplyTeNewAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-08-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class BaseinfochgTaShowAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
  public static final String PAGINATION_KEY = "org.xpup.hafmis.sysloan.contractchg.baseinfochg.action.BaseinfochgTaShowAC";
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

    Pagination pagination = getPagination(PAGINATION_KEY, request);
    PaginationUtils.updatePagination(pagination, request);
    SecurityInfo securityInfo = (SecurityInfo) request.getSession()
    .getAttribute("SecurityInfo");
    LoanapplyTeNewAF loanapplytenewAF=new LoanapplyTeNewAF();
    
    IBaseinfochgBS baseinfochgBS = (IBaseinfochgBS) BSUtils.getBusinessService("baseinfochgBS", this, mapping.getModuleConfig());
    
    try {
      loanapplytenewAF= baseinfochgBS.showBaseinfochgTa(pagination,securityInfo);
    } catch (Exception e) {
      e.printStackTrace();
    }
    try {
      loanapplytenewAF.setBuyHouseTypeMap(BusiTools.listBusiProperty(BusiConst.PLHOUSETYPE));
    } catch (Exception e) {
      e.printStackTrace();
    }
    request.setAttribute("loanapplytenewAF", loanapplytenewAF);
		return mapping.findForward("baseinfochgta");
	}
  
   private Pagination getPagination(String paginationKey,HttpServletRequest request) {
      Pagination pagination = (Pagination) request.getSession().getAttribute(
          paginationKey);
      if (pagination == null) {
        pagination = new Pagination(0, 10, 1, "p1.contract_st", "DESC", new HashMap(0));
        request.getSession().setAttribute(paginationKey, pagination);
      }
      return pagination;
    }
}