/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.loanapply.loanreturnedbyfund.action;


import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.LookupDispatchAction;
import org.xpup.common.exception.BusinessException;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.common.form.IdAF;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysloan.common.domain.entity.AssistantBorrower;
import org.xpup.hafmis.sysloan.common.domain.entity.Borrower;
import org.xpup.hafmis.sysloan.common.domain.entity.BorrowerAcc;
import org.xpup.hafmis.sysloan.common.domain.entity.BorrowerLoanInfo;
import org.xpup.hafmis.sysloan.loanapply.loanreturnedbyfund.bsinterface.ILoanreturnedbyfundBS;
import org.xpup.hafmis.sysloan.loanapply.loanreturnedbyfund.dto.LoanreturnedbyfundSaveDTO;
import org.xpup.hafmis.sysloan.loanapply.loanreturnedbyfund.form.LoanreturnedbyfundTaAF;

/** 
 * MyEclipse Struts
 * Creation date: 09-26-2007
 * 
 * XDoclet definition:
 * @struts.action path="loanapplytbtopmaintianAC" name="idAF" scope="request" validate="true"
 */
public class LoanreturnedbyfundTaMainTianAC extends LookupDispatchAction {
	
  protected Map getKeyMethodMap() {
    Map map = new HashMap();
   
    map.put("button.sure", "sure");
    return map;
  }

  public ActionForward sure(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) throws BusinessException {
    ActionMessages messages =null;
    LoanreturnedbyfundTaAF loanreturnedbyfundTaAF = new LoanreturnedbyfundTaAF();
    try {
      String contractId=(String)request.getSession().getAttribute("contractId");
      loanreturnedbyfundTaAF=(LoanreturnedbyfundTaAF)request.getSession().getAttribute("loanreturnedbyfundTaAF");
      IdAF idAF=(IdAF)form;   
      String id[]=idAF.getRowArray();
      SecurityInfo securityInfo = (SecurityInfo) request.getSession()
      .getAttribute("SecurityInfo");
      String pl009id="";
      ILoanreturnedbyfundBS loanreturnedbyfundBS = (ILoanreturnedbyfundBS) BSUtils.getBusinessService(
          "loanreturnedbyfundBS", this, mapping.getModuleConfig());
      
      LoanreturnedbyfundSaveDTO loanreturnedbyfundSaveDTO1 = new LoanreturnedbyfundSaveDTO();
      
      String loanKouAcc=loanreturnedbyfundBS.get_loanKouAcc(contractId);
      loanreturnedbyfundSaveDTO1.setContractId(contractId);
      loanreturnedbyfundSaveDTO1.setLoanKouAcc(loanKouAcc);
      loanreturnedbyfundSaveDTO1.setEmpId(loanreturnedbyfundTaAF.getBorrow_empid());
      loanreturnedbyfundSaveDTO1.setEmpName(loanreturnedbyfundTaAF.getBorrowerName());
      loanreturnedbyfundSaveDTO1.setOrgId(loanreturnedbyfundTaAF.getBorrow_orgid());
      loanreturnedbyfundSaveDTO1.setCardNum(loanreturnedbyfundTaAF.getBorrower_cardNum());
      
      loanreturnedbyfundSaveDTO1.setEmpId_s(loanreturnedbyfundTaAF.getBorrow_s_empid());
      loanreturnedbyfundSaveDTO1.setEmpName_s(loanreturnedbyfundTaAF.getBorrow_s_empname());
      loanreturnedbyfundSaveDTO1.setOrgId_s(loanreturnedbyfundTaAF.getBorrow_s_orgid());
      loanreturnedbyfundSaveDTO1.setCardNum_s(loanreturnedbyfundTaAF.getBorrow_s_cardnum());
      
      loanreturnedbyfundSaveDTO1.setEmpId_sa(loanreturnedbyfundTaAF.getBorrow_s_empida());
      loanreturnedbyfundSaveDTO1.setEmpName_sa(loanreturnedbyfundTaAF.getBorrow_s_empnamea());
      loanreturnedbyfundSaveDTO1.setOrgId_sa(loanreturnedbyfundTaAF.getBorrow_s_orgida());
      loanreturnedbyfundSaveDTO1.setCardNum_sa(loanreturnedbyfundTaAF.getBorrow_s_cardnuma());
      
      loanreturnedbyfundSaveDTO1.setEmpId_sb(loanreturnedbyfundTaAF.getBorrow_s_empidb());
      loanreturnedbyfundSaveDTO1.setEmpName_sb(loanreturnedbyfundTaAF.getBorrow_s_empnameb());
      loanreturnedbyfundSaveDTO1.setOrgId_sb(loanreturnedbyfundTaAF.getBorrow_s_orgidb());
      loanreturnedbyfundSaveDTO1.setCardNum_sb(loanreturnedbyfundTaAF.getBorrow_s_cardnumb());
      
      pl009id=loanreturnedbyfundBS.LoanreturnedbyfundFindID("402881651bde207d011bde2453110002", "5");
      String time=(String)request.getSession().getAttribute("time");
      String xieyiNum="";
      loanreturnedbyfundBS.LoanreturnedbyfundSaveAll(loanreturnedbyfundSaveDTO1, id, securityInfo, pl009id, contractId,time,xieyiNum,"402881651bde207d011bde2453110002");
      request.getSession().setAttribute("xieYiNum", xieyiNum);
      request.setAttribute("print", "1");
      BorrowerAcc borrowerAcc=loanreturnedbyfundBS.findBorrowerAcc(contractId);
      String bankName=loanreturnedbyfundBS.findBankName(borrowerAcc.getLoanBankId().toString());
      String houseAddr=loanreturnedbyfundBS.findHouseAddr(contractId);
      request.setAttribute("bankName", bankName);
      request.setAttribute("houseAddr", houseAddr);
      request.setAttribute("username", securityInfo.getRealName());
      request.setAttribute("loanstartdate", borrowerAcc.getLoanStartDate());
      request.setAttribute("loanreturnedbyfundTaAF", loanreturnedbyfundTaAF);
    }catch(BusinessException e) {
      e.printStackTrace();
      request.setAttribute("error", e
          .getMessage());
      messages = new ActionMessages();
      messages.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(e
          .getMessage(), false));
      saveErrors(request, messages);
      return mapping.findForward("to_showloanreturnedbyfundTa");
    } catch (Exception e) {
      e.printStackTrace();
    }
    return mapping.findForward("to_printloanreturnedbyfundTa");
  }

}