/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.querystatistics.querycongeallog.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.common.util.Pagination;
import org.xpup.common.util.PaginationUtils;
import org.xpup.hafmis.orgstrct.dto.OfficeDto;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysloan.querystatistics.querystatistics.querycongeallog.bsinterface.IQueryCongeallogBS;
import org.xpup.hafmis.sysloan.querystatistics.querystatistics.querycongeallog.form.QueryCongeallogAF;
import org.xpup.security.common.domain.Userslogincollbank;

/**
 * MyEclipse Struts Creation date: 01-29-2008 XDoclet definition:
 * 
 * @struts.action path="/queryCongeallogShowAC" name="idAF" scope="request"
 *                validate="true"
 */
public class QueryCongeallogShowAC extends Action {
  /*
   * Generated Methods
   */

  /**
   * Method execute
   * 
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   */

  public static final String PAGINATION_KEY = "org.xpup.hafmis.sysloan.querystatistics.querystatistics.querycongeallog.action.QueryCongeallogShowAC";

  public ActionForward execute(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {
    // IdAF idAF = (IdAF) form;// TODO Auto-generated method stub
    try {
      Pagination pagination = getPagination(PAGINATION_KEY, request);
      PaginationUtils.updatePagination(pagination, request);
      SecurityInfo securityInfo = (SecurityInfo) request.getSession()
          .getAttribute("SecurityInfo");
      IQueryCongeallogBS queryCongeallogBS = (IQueryCongeallogBS) BSUtils
          .getBusinessService("queryCongeallogBS", this, mapping
              .getModuleConfig());

      // 求办事处
      List temp_officeList = securityInfo.getOfficeList();
      List li = new ArrayList();
      for (int i = 0; i < temp_officeList.size(); i++) {
        OfficeDto officedto = null;
        officedto = (OfficeDto) temp_officeList.get(i);
        li.add(new org.apache.struts.util.LabelValueBean(officedto
            .getOfficeName(), officedto.getOfficeCode()));
      }

      // 求放款银行
      List temp_DkbankList = securityInfo.getDkUserBankList();
      List libank = new ArrayList();
      for (int i = 0; i < temp_DkbankList.size(); i++) {
        Userslogincollbank u = null;
        u = (Userslogincollbank) temp_DkbankList.get(i);
        libank.add(new org.apache.struts.util.LabelValueBean(u
            .getCollBankName(), u.getCollBankId().toString()));
      }

      request.setAttribute("officelist", li);
      request.setAttribute("dkbanklist", libank);

      QueryCongeallogAF queryCongeallogAF = null;
      
      queryCongeallogAF = new QueryCongeallogAF();
      //冻结表信息LIST
      List list_temp =null;
      list_temp= new ArrayList();
      list_temp = queryCongeallogBS.queryCongeallogList(pagination, securityInfo);
      String bankId = (String)pagination.getQueryCriterions().get("bankId");
      queryCongeallogAF.setBankId(bankId);
      queryCongeallogAF.setList(list_temp);
      //冻结表信息记录数
      int count_temp = queryCongeallogBS.queryCongeallogListCount(pagination, securityInfo);
    
      pagination.setNrOfElements(count_temp);
      request.setAttribute("queryCongeallogAF", queryCongeallogAF);
    //  request.getSession().setAttribute("allList", allList);
      request.getSession().setAttribute("pagination", pagination);
    } catch (Exception e) {
      e.printStackTrace();
    }
    return mapping.findForward("queryCongeallog_show");
  }

  private Pagination getPagination(String paginationKey,
      HttpServletRequest request) {
    Pagination pagination = (Pagination) request.getSession().getAttribute(
        paginationKey);
    if (pagination == null) {
      pagination = new Pagination(0, 10, 1, "p210.id", "DESC", new HashMap(0));
      request.getSession().setAttribute(paginationKey, pagination);
    }
    return pagination;
  }

}