/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.querystatistics.querycongeallog.action;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.Pagination;
import org.xpup.hafmis.sysloan.querystatistics.querystatistics.querycongeallog.form.QueryCongeallogAF;

/** 
 * MyEclipse Struts
 * Creation date: 01-29-2008
 * 
 * XDoclet definition:
 * @struts.action path="/queryCongeallogFindAC" name="queryCongeallogAF" scope="request" validate="true"
 */
public class QueryCongeallogFindAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    try {
      QueryCongeallogAF queryCongeallogAF = (QueryCongeallogAF) form;// TODO Auto-generated method stub
      HashMap criterions = makeCriterionsMap(queryCongeallogAF);
      Pagination pagination = new Pagination(0, 10, 1, "p210.id", "DESC",criterions);
      String paginationKey = QueryCongeallogShowAC.PAGINATION_KEY;
      request.getSession().setAttribute(paginationKey, pagination);
    } catch (Exception e) {
      e.printStackTrace();
    }
    return mapping.findForward("queryCongeallogShowAC");
	}
  
   protected HashMap makeCriterionsMap(QueryCongeallogAF queryCongeallogAF) {
     HashMap map = new HashMap();
     try {
      String officeName = queryCongeallogAF.getOfficeName().trim();
      if (!( officeName== null || "".equals(officeName.trim()))) {
        map.put("officeName", officeName);
      }
      String bankId = queryCongeallogAF.getBankId().trim();
      if (!( bankId== null || "".equals(bankId.trim()))) {
        map.put("bankId", bankId);
      }
      String contractId = queryCongeallogAF.getContractId().trim();
      if (!( contractId== null || "".equals(contractId.trim()))) {
        map.put("contractId", contractId);
      }
      String empName = queryCongeallogAF.getEmpName().trim();
      if (!( empName== null || "".equals(empName.trim()))) {
        map.put("empName", empName);
      }
      String status = queryCongeallogAF.getStatus().trim();
      if (!( status== null || "".equals(status.trim()))) {
        map.put("status", status);
      }
      String type = queryCongeallogAF.getType().trim();
      if (!( type== null || "".equals(type.trim()))) {
        map.put("type", type);
      }
      String cardNum = queryCongeallogAF.getCardNum().trim();
      if (!( cardNum== null || "".equals(cardNum.trim()))) {
        map.put("cardNum", cardNum);
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
    return map;
   }
}