/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.querystatistics.querycongeallog.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-29-2008
 * 
 * XDoclet definition:
 * @struts.form name="queryCongeallogAF"
 */
public class QueryCongeallogAF extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
   * 
   */
  private static final long serialVersionUID = -2367866364100715804L;

  /** bankId property */
	private String bankId = "";

	/** officeName property */
	private String officeName = "";

	/** type property */
	private String type = "";

	/** empName property */
	private String empName = "";

	/** status property */
	private String status = "";

	/** cardNum property */
	private String cardNum = "";

	/** contractId property */
	private String contractId = "";
  
  private List list=new ArrayList();   

	/*
	 * Generated Methods
	 */

	public List getList() {
    return list;
  }

  public void setList(List list) {
    this.list = list;
  }

  /** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the bankId.
	 * @return String
	 */
	public String getBankId() {
		return bankId;
	}

	/** 
	 * Set the bankId.
	 * @param bankId The bankId to set
	 */
	public void setBankId(String bankId) {
		this.bankId = bankId;
	}

	/** 
	 * Returns the officeName.
	 * @return String
	 */
	public String getOfficeName() {
		return officeName;
	}

	/** 
	 * Set the officeName.
	 * @param officeName The officeName to set
	 */
	public void setOfficeName(String officeName) {
		this.officeName = officeName;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the empName.
	 * @return String
	 */
	public String getEmpName() {
		return empName;
	}

	/** 
	 * Set the empName.
	 * @param empName The empName to set
	 */
	public void setEmpName(String empName) {
		this.empName = empName;
	}

	/** 
	 * Returns the status.
	 * @return String
	 */
	public String getStatus() {
		return status;
	}

	/** 
	 * Set the status.
	 * @param status The status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/** 
	 * Returns the cardNum.
	 * @return String
	 */
	public String getCardNum() {
		return cardNum;
	}

	/** 
	 * Set the cardNum.
	 * @param cardNum The cardNum to set
	 */
	public void setCardNum(String cardNum) {
		this.cardNum = cardNum;
	}

	/** 
	 * Returns the contractId.
	 * @return String
	 */
	public String getContractId() {
		return contractId;
	}

	/** 
	 * Set the contractId.
	 * @param contractId The contractId to set
	 */
	public void setContractId(String contractId) {
		this.contractId = contractId;
	}
}