package org.xpup.hafmis.common.util.enumerate;

import org.xpup.hafmis.common.util.BusiConst;
/**
 * 主管部门
 * @author 王玲
 *2007-6-29
 */
public class Authorities extends AbsBusiProMap {

  static final long serialVersionUID = -6831497426265030966L;

  static final Integer[] keys = { 
    new Integer(BusiConst.AUTHORITIES_1 ), 
    new Integer(BusiConst.AUTHORITIES_2 ), 
    new Integer(BusiConst.AUTHORITIES_3 ), 
    new Integer(BusiConst.AUTHORITIES_4 ), 
    new Integer(BusiConst.AUTHORITIES_5 ), 
    new Integer(BusiConst.AUTHORITIES_6 ), 
    new Integer(BusiConst.AUTHORITIES_7 ), 
    new Integer(BusiConst.AUTHORITIES_8 ), 
    new Integer(BusiConst.AUTHORITIES_9 ), 
    new Integer(BusiConst.AUTHORITIES_10 ), 
    new Integer(BusiConst.AUTHORITIES_11 ), 
    new Integer(BusiConst.AUTHORITIES_12 ), 
    new Integer(BusiConst.AUTHORITIES_13 ), 
    new Integer(BusiConst.AUTHORITIES_14 ), 
    new Integer(BusiConst.AUTHORITIES_15 ), 
    new Integer(BusiConst.AUTHORITIES_16 ), 
    new Integer(BusiConst.AUTHORITIES_17 ), 
    new Integer(BusiConst.AUTHORITIES_18 ), 
    new Integer(BusiConst.AUTHORITIES_19 ), 
    new Integer(BusiConst.AUTHORITIES_20 ), 
   
    new Integer(BusiConst.AUTHORITIES_22 ), 
    new Integer(BusiConst.AUTHORITIES_23 ), 
    new Integer(BusiConst.AUTHORITIES_24 ), 
    new Integer(BusiConst.AUTHORITIES_25 ), 
    new Integer(BusiConst.AUTHORITIES_26 ), 
    new Integer(BusiConst.AUTHORITIES_27 ), 
    new Integer(BusiConst.AUTHORITIES_28 ), 
    new Integer(BusiConst.AUTHORITIES_29 ), 
    new Integer(BusiConst.AUTHORITIES_30 ), 
    new Integer(BusiConst.AUTHORITIES_31 ), 
    new Integer(BusiConst.AUTHORITIES_32 ), 
    new Integer(BusiConst.AUTHORITIES_33 ), 
    new Integer(BusiConst.AUTHORITIES_34 ), 
    new Integer(BusiConst.AUTHORITIES_35 ), 
    new Integer(BusiConst.AUTHORITIES_36 ), 
    new Integer(BusiConst.AUTHORITIES_37 ), 
    new Integer(BusiConst.AUTHORITIES_38 ), 
    new Integer(BusiConst.AUTHORITIES_39 ), 
    new Integer(BusiConst.AUTHORITIES_40 ), 

    new Integer(BusiConst.AUTHORITIES_42 ), 
    new Integer(BusiConst.AUTHORITIES_43 ), 
    new Integer(BusiConst.AUTHORITIES_44 ), 
    new Integer(BusiConst.AUTHORITIES_45 ), 
    new Integer(BusiConst.AUTHORITIES_46 ), 
    new Integer(BusiConst.AUTHORITIES_47 ), 
    new Integer(BusiConst.AUTHORITIES_48 ), 
    new Integer(BusiConst.AUTHORITIES_49 ), 
    new Integer(BusiConst.AUTHORITIES_50 ), 
    new Integer(BusiConst.AUTHORITIES_51 ), 
    new Integer(BusiConst.AUTHORITIES_52 ), 
    new Integer(BusiConst.AUTHORITIES_53 ), 
    new Integer(BusiConst.AUTHORITIES_54 ), 
    new Integer(BusiConst.AUTHORITIES_55 ), 
    new Integer(BusiConst.AUTHORITIES_56 ), 
    new Integer(BusiConst.AUTHORITIES_57 ), 
    new Integer(BusiConst.AUTHORITIES_58 ), 
    new Integer(BusiConst.AUTHORITIES_59 ), 
    new Integer(BusiConst.AUTHORITIES_60 ), 
    new Integer(BusiConst.AUTHORITIES_61 ),
    new Integer(BusiConst.AUTHORITIES_62 ), 
     new Integer(BusiConst.AUTHORITIES_ZHONGZHI),
     new Integer(BusiConst.AUTHORITIES_SHENGZHI),
     new Integer(BusiConst.AUTHORITIES_SHIZHI),
     new Integer(BusiConst.AUTHORITIES_SHIJIYIXIA),
     new Integer(BusiConst.AUTHORITIES_OTHER)
     };

   static final String[] values = { "组织部",
     "气象局",
     "市直机关工委",
     "市残联",
     "团市委",
     "科技局",
     "烟草公司",
     "体育局",
     "供销社",
     "西市区政府",
     "老边区政府",
     "纺织协会",
     "统计局",
     "站前区政府",
     "质量技术监督局",
     "省直",
     "水利局",
     "营口港务集团",
     "海洋渔业管理局",
     "发展改革委员会",
     "市委统战部",
     "其他",
     "中国联通辽宁分公司",
     "日报社",
     "教育局",
     "公用事业与房产局",
     "财政局",
     "经委",
     "国土资源局",
     "文化局",
     "公安局",
     "规划建设委员会",
     "市委",
     "市政府",
     "旅游局",
     "交通局",
     "卫生局",
     "民政局",
     "环保局",
     "国税局",
     "人事局",
     "公检法",
     "检察院",
     "法院",
     "金融",
     "保险",
     "农机局",
     "老龄办",
     "商业局",
     "林业局",
     "农委",
     "动物卫生监督管理局",
     "外经贸局",
     "安全生产监督管理局",
     "宣传部",
     "纪检委",
     "计生委",
     "高速公路管理局",
     "文联",
     "工商局",
"中直","省直","市直","市级以下","其他" };
  public Authorities()
  {
    this.putValues(keys,values);
  }
}
