/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.collloanbackcheck.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public class CollLoanbackclearForwardAC extends Action {
  public static final String PAGINATION_KEY = "org.xpup.hafmis.syscollection.collloanbackcheck.action.CollLoanbackcheckShowAC";

  public ActionForward execute(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {

    HttpSession session = request.getSession();
    session.setAttribute(PAGINATION_KEY, null);
    session.setAttribute("flag", "2");
    return mapping.findForward(getForword());
  }
  protected String getForword() {
    return "collLoanbackcheckShowAC";
  }
}