/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.loanapply.loanapply.form;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 10-03-2007 XDoclet definition:
 * 
 * @struts.form name="loanapplytenewAF"
 */
public class LoanapplyTeNewAF extends ActionForm {

  private String count;
  
  private String contractId;

  private String borrowerName;

  private String empId;

  private String cardNum;

  private String buyHouseType;

  private Map buyHouseTypeMap = new HashMap();

  private String contranct_st;

  private Map contranct_stMap = new HashMap();

  private List list = new ArrayList();
  
  private List lis = new ArrayList();

  public String getBorrowerName() {
    return borrowerName;
  }

  public void setBorrowerName(String borrowerName) {
    this.borrowerName = borrowerName;
  }

  public String getBuyHouseType() {
    return buyHouseType;
  }

  public void setBuyHouseType(String buyHouseType) {
    this.buyHouseType = buyHouseType;
  }

  public String getCardNum() {
    return cardNum;
  }

  public void setCardNum(String cardNum) {
    this.cardNum = cardNum;
  }

  public String getContractId() {
    return contractId;
  }

  public void setContractId(String contractId) {
    this.contractId = contractId;
  }

  public String getContranct_st() {
    return contranct_st;
  }

  public void setContranct_st(String contranct_st) {
    this.contranct_st = contranct_st;
  }

  public String getEmpId() {
    return empId;
  }

  public void setEmpId(String empId) {
    this.empId = empId;
  }

  public List getList() {
    return list;
  }

  public void setList(List list) {
    this.list = list;
  }

  public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
    // TODO Auto-generated method stub
    return null;
  }

  /**
   * Method reset
   * 
   * @param mapping
   * @param request
   */
  public void reset(ActionMapping mapping, HttpServletRequest request) {
    // TODO Auto-generated method stub
  }

  public Map getBuyHouseTypeMap() {
    return buyHouseTypeMap;
  }

  public void setBuyHouseTypeMap(Map buyHouseTypeMap) {
    this.buyHouseTypeMap = buyHouseTypeMap;
  }

  public Map getContranct_stMap() {
    return contranct_stMap;
  }

  public void setContranct_stMap(Map contranct_stMap) {
    this.contranct_stMap = contranct_stMap;
  }

  public List getLis() {
    return lis;
  }

  public void setLis(List lis) {
    this.lis = lis;
  }

  public String getCount() {
    return count;
  }

  public void setCount(String count) {
    this.count = count;
  }
}