/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.loanapply.loanapply.form;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-02-2007
 * 
 * XDoclet definition:
 * @struts.form name="loanapplytdnewAF"
 */
public class LoanapplyTdNewAF extends ActionForm {
  private String spid;//用于判断是否是特殊申请人
  private String isNeedDel;//是否走过扫描
  private String photoUrl;//图片路径
  private String coodm;
  private String office;
  
  private String contractId;
  private String borrowerName;
  private String cardKind;
  private String cardNum;
  
  private String loanMoney;
  private String loanMoneyBig;
  private String loanMoneyWY;
  
  private String loantimeLimit;
  private String loanMood;
  private Map loanMoodMap = new HashMap();
  
  private String loanMonthRate;
  private String loanPoundage="0";
  
  private String firstLoanMoney;
  private String corpusInterest;
  
  private String temp_ty;
  private String loanMonthRatess;  
 
  
  private String entireYearMoney="";//整年期总还款额
  private String houseTotlePrice="";
  private String firstTol="";
  /** 最大贷款期限 **/
  private int loanMonthLimit;
  /** 最大贷款金额 **/
  private BigDecimal loanMoneyLimit;
  
  private String developerName = "";
  
	public String getDeveloperName() {
    return developerName;
  }

  public void setDeveloperName(String developerName) {
    this.developerName = developerName;
  }

  public String getEntireYearMoney() {
    return entireYearMoney;
  }

  public void setEntireYearMoney(String entireYearMoney) {
    this.entireYearMoney = entireYearMoney;
  }

  public String getTemp_ty() {
    return temp_ty;
  }

  public void setTemp_ty(String temp_ty) {
    this.temp_ty = temp_ty;
  }

  public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

  public String getBorrowerName() {
    return borrowerName;
  }

  public void setBorrowerName(String borrowerName) {
    this.borrowerName = borrowerName;
  }

  public String getCardKind() {
    return cardKind;
  }

  public void setCardKind(String cardKind) {
    this.cardKind = cardKind;
  }

  public String getCardNum() {
    return cardNum;
  }

  public void setCardNum(String cardNum) {
    this.cardNum = cardNum;
  }

  public String getContractId() {
    return contractId;
  }

  public void setContractId(String contractId) {
    this.contractId = contractId;
  }

  public String getCorpusInterest() {
    return corpusInterest;
  }

  public void setCorpusInterest(String corpusInterest) {
    this.corpusInterest = corpusInterest;
  }

  public String getFirstLoanMoney() {
    return firstLoanMoney;
  }

  public void setFirstLoanMoney(String firstLoanMoney) {
    this.firstLoanMoney = firstLoanMoney;
  }

  public String getLoanMoney() {
    return loanMoney;
  }

  public void setLoanMoney(String loanMoney) {
    this.loanMoney = loanMoney;
  }

  public String getLoanMoneyBig() {
    return loanMoneyBig;
  }

  public void setLoanMoneyBig(String loanMoneyBig) {
    this.loanMoneyBig = loanMoneyBig;
  }

  public String getLoanMonthRate() {
    return loanMonthRate;
  }

  public void setLoanMonthRate(String loanMonthRate) {
    this.loanMonthRate = loanMonthRate;
  }

  public String getLoanMood() {
    return loanMood;
  }

  public void setLoanMood(String loanMood) {
    this.loanMood = loanMood;
  }

  public String getLoanPoundage() {
    return loanPoundage;
  }

  public void setLoanPoundage(String loanPoundage) {
    this.loanPoundage = loanPoundage;
  }

  public String getLoantimeLimit() {
    return loantimeLimit;
  }

  public void setLoantimeLimit(String loantimeLimit) {
    this.loantimeLimit = loantimeLimit;
  }

  public String getOffice() {
    return office;
  }

  public void setOffice(String office) {
    this.office = office;
  }

  public String getCoodm() {
    return coodm;
  }

  public void setCoodm(String coodm) {
    this.coodm = coodm;
  }

  public String getLoanMonthRatess() {
    return loanMonthRatess;
  }

  public void setLoanMonthRatess(String loanMonthRatess) {
    this.loanMonthRatess = loanMonthRatess;
  }

  public String getSpid() {
    return spid;
  }

  public void setSpid(String spid) {
    this.spid = spid;
  }

  public String getIsNeedDel() {
    return isNeedDel;
  }

  public void setIsNeedDel(String isNeedDel) {
    this.isNeedDel = isNeedDel;
  }

  public String getPhotoUrl() {
    return photoUrl;
  }

  public void setPhotoUrl(String photoUrl) {
    this.photoUrl = photoUrl;
  }

  public Map getLoanMoodMap() {
    return loanMoodMap;
  }

  public void setLoanMoodMap(Map loanMoodMap) {
    this.loanMoodMap = loanMoodMap;
  }

  public String getHouseTotlePrice() {
    return houseTotlePrice;
  }

  public void setHouseTotlePrice(String houseTotlePrice) {
    this.houseTotlePrice = houseTotlePrice;
  }

  public String getFirstTol() {
    return firstTol;
  }

  public void setFirstTol(String firstTol) {
    this.firstTol = firstTol;
  }

  public String getLoanMoneyWY() {
    return loanMoneyWY;
  }

  public void setLoanMoneyWY(String loanMoneyWY) {
    this.loanMoneyWY = loanMoneyWY;
  }

  public BigDecimal getLoanMoneyLimit() {
    return loanMoneyLimit;
  }

  public void setLoanMoneyLimit(BigDecimal loanMoneyLimit) {
    this.loanMoneyLimit = loanMoneyLimit;
  }

  public int getLoanMonthLimit() {
    return loanMonthLimit;
  }

  public void setLoanMonthLimit(int loanMonthLimit) {
    this.loanMonthLimit = loanMonthLimit;
  }
}