/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.loanapply.loanapply.form;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

public class LoanapplyTcNewAF extends ActionForm {
  
  private String isNeedDel;// 是否走过扫描

  private String photoUrl;// 图片路径

  private String temp_floornum;

  private String coodm;// 所有的AF里都叫这个名字，用来判断是否从维护中的超链接过来的

  private List banklist = new ArrayList();

  private List floorlist = new ArrayList();

  private List floornumlist = new ArrayList();

  private String buyhouseorgid;// 是购房单位的Id，根据它关联pl005求单位名称，即是表内主键

  private String temp_type;

  private String temp_type_remind;// 判断是否从维护过来的

  private String contractId;

  private String borrowerName;

  private String orgName;

  private String headId;

  private String developerTel;

  private String developerPaybank;

  private String banNamehidden;

  private String developerPaybankAAcc;

  private String floorId;

  private String floorNum;

  private String floorNumber;// 此属性是页面显示的楼盘号

  private String roomNum;

  private String firstPay;

  private String firstTol;

  private String houseTotlePrice;

  private String housePrice;

  private String buyHouseContractId;

  private String houseArea;

  private String isNowhouse;

  private Map isNowhouseMap = new HashMap();

  private String overDate;

  private String buildRightNum;

  private String agreementDate;

  private String houseAddr;

  private String bargainorName;

  private String bargainorCardKind;

  private Map bargainorCardKindMap = new HashMap();

  private String bargainorCardNum;

  private String bargainorTel;

  private String bargainorHousepropertyCode;

  private String bargainorMobile;

  private String bargainorHouseAddr;

  private String bargainorPaybank;

  private String bargainorPaybankAcc;

  private String bargainorHouseArea;

  private String bargainorTotlePrice;

  private String bargainorHouseAge;

  private String bargainorAgreementDate;

  private String houseType;// 单选按钮

  private String houseTypehidden;// 房子类型的隐藏域

  private String houseTypetemp = "0";// 用来判断页面上的扫描按钮禁用，也就是说 来说明有没有购房信息

  private String remark1;

  private String remark2;

  private String hiddencheckFloornum;

  private String fundBank = "";

  private String fundBankAcc = "";
  
  private String speAppFlag = "";

  public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
    // TODO Auto-generated method stub
    return null;
  }

  /**
   * Method reset
   * 
   * @param mapping
   * @param request
   */
  public void reset(ActionMapping mapping, HttpServletRequest request) {
    // TODO Auto-generated method stub
  }

  public String getAgreementDate() {
    return agreementDate;
  }

  public void setAgreementDate(String agreementDate) {
    this.agreementDate = agreementDate;
  }

  public String getBargainorAgreementDate() {
    return bargainorAgreementDate;
  }

  public void setBargainorAgreementDate(String bargainorAgreementDate) {
    this.bargainorAgreementDate = bargainorAgreementDate;
  }

  public String getBargainorCardKind() {
    return bargainorCardKind;
  }

  public void setBargainorCardKind(String bargainorCardKind) {
    this.bargainorCardKind = bargainorCardKind;
  }

  public String getBargainorCardNum() {
    return bargainorCardNum;
  }

  public void setBargainorCardNum(String bargainorCardNum) {
    this.bargainorCardNum = bargainorCardNum;
  }

  public String getBargainorHouseAddr() {
    return bargainorHouseAddr;
  }

  public void setBargainorHouseAddr(String bargainorHouseAddr) {
    this.bargainorHouseAddr = bargainorHouseAddr;
  }

  public String getBargainorHouseAge() {
    return bargainorHouseAge;
  }

  public void setBargainorHouseAge(String bargainorHouseAge) {
    this.bargainorHouseAge = bargainorHouseAge;
  }

  public String getBargainorHouseArea() {
    return bargainorHouseArea;
  }

  public void setBargainorHouseArea(String bargainorHouseArea) {
    this.bargainorHouseArea = bargainorHouseArea;
  }

  public String getBargainorHousepropertyCode() {
    return bargainorHousepropertyCode;
  }

  public void setBargainorHousepropertyCode(String bargainorHousepropertyCode) {
    this.bargainorHousepropertyCode = bargainorHousepropertyCode;
  }

  public String getBargainorMobile() {
    return bargainorMobile;
  }

  public void setBargainorMobile(String bargainorMobile) {
    this.bargainorMobile = bargainorMobile;
  }

  public String getBargainorName() {
    return bargainorName;
  }

  public void setBargainorName(String bargainorName) {
    this.bargainorName = bargainorName;
  }

  public String getBargainorPaybank() {
    return bargainorPaybank;
  }

  public void setBargainorPaybank(String bargainorPaybank) {
    this.bargainorPaybank = bargainorPaybank;
  }

  public String getBargainorPaybankAcc() {
    return bargainorPaybankAcc;
  }

  public void setBargainorPaybankAcc(String bargainorPaybankAcc) {
    this.bargainorPaybankAcc = bargainorPaybankAcc;
  }

  public String getBargainorTel() {
    return bargainorTel;
  }

  public void setBargainorTel(String bargainorTel) {
    this.bargainorTel = bargainorTel;
  }

  public String getBargainorTotlePrice() {
    return bargainorTotlePrice;
  }

  public void setBargainorTotlePrice(String bargainorTotlePrice) {
    this.bargainorTotlePrice = bargainorTotlePrice;
  }

  public String getBuildRightNum() {
    return buildRightNum;
  }

  public void setBuildRightNum(String buildRightNum) {
    this.buildRightNum = buildRightNum;
  }

  public String getBuyHouseContractId() {
    return buyHouseContractId;
  }

  public void setBuyHouseContractId(String buyHouseContractId) {
    this.buyHouseContractId = buyHouseContractId;
  }

  public String getContractId() {
    return contractId;
  }

  public void setContractId(String contractId) {
    this.contractId = contractId;
  }

  public String getDeveloperPaybank() {
    return developerPaybank;
  }

  public void setDeveloperPaybank(String developerPaybank) {
    this.developerPaybank = developerPaybank;
  }

  public String getDeveloperPaybankAAcc() {
    return developerPaybankAAcc;
  }

  public void setDeveloperPaybankAAcc(String developerPaybankAAcc) {
    this.developerPaybankAAcc = developerPaybankAAcc;
  }

  public String getDeveloperTel() {
    return developerTel;
  }

  public void setDeveloperTel(String developerTel) {
    this.developerTel = developerTel;
  }

  public String getFirstPay() {
    return firstPay;
  }

  public void setFirstPay(String firstPay) {
    this.firstPay = firstPay;
  }

  public String getFloorId() {
    return floorId;
  }

  public void setFloorId(String floorId) {
    this.floorId = floorId;
  }

  public String getFloorNum() {
    return floorNum;
  }

  public void setFloorNum(String floorNum) {
    this.floorNum = floorNum;
  }

  public String getHeadId() {
    return headId;
  }

  public void setHeadId(String headId) {
    this.headId = headId;
  }

  public String getHouseAddr() {
    return houseAddr;
  }

  public void setHouseAddr(String houseAddr) {
    this.houseAddr = houseAddr;
  }

  public String getHouseArea() {
    return houseArea;
  }

  public void setHouseArea(String houseArea) {
    this.houseArea = houseArea;
  }

  public String getHouseTotlePrice() {
    return houseTotlePrice;
  }

  public void setHouseTotlePrice(String houseTotlePrice) {
    this.houseTotlePrice = houseTotlePrice;
  }

  public String getHouseType() {
    return houseType;
  }

  public void setHouseType(String houseType) {
    this.houseType = houseType;
  }

  public String getIsNowhouse() {
    return isNowhouse;
  }

  public void setIsNowhouse(String isNowhouse) {
    this.isNowhouse = isNowhouse;
  }

  public String getOverDate() {
    return overDate;
  }

  public void setOverDate(String overDate) {
    this.overDate = overDate;
  }

  public String getRemark1() {
    return remark1;
  }

  public void setRemark1(String remark1) {
    this.remark1 = remark1;
  }

  public String getRemark2() {
    return remark2;
  }

  public void setRemark2(String remark2) {
    this.remark2 = remark2;
  }

  public String getRoomNum() {
    return roomNum;
  }

  public void setRoomNum(String roomNum) {
    this.roomNum = roomNum;
  }

  public String getBorrowerName() {
    return borrowerName;
  }

  public void setBorrowerName(String borrowerName) {
    this.borrowerName = borrowerName;
  }

  public String getOrgName() {
    return orgName;
  }

  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }

  public String getHousePrice() {
    return housePrice;
  }

  public void setHousePrice(String housePrice) {
    this.housePrice = housePrice;
  }

  public String getFirstTol() {
    return firstTol;
  }

  public void setFirstTol(String firstTol) {
    this.firstTol = firstTol;
  }

  public Map getBargainorCardKindMap() {
    return bargainorCardKindMap;
  }

  public void setBargainorCardKindMap(Map bargainorCardKindMap) {
    this.bargainorCardKindMap = bargainorCardKindMap;
  }

  public String getTemp_type() {
    return temp_type;
  }

  public void setTemp_type(String temp_type) {
    this.temp_type = temp_type;
  }

  public List getBanklist() {
    return banklist;
  }

  public void setBanklist(List banklist) {
    this.banklist = banklist;
  }

  public List getFloorlist() {
    return floorlist;
  }

  public void setFloorlist(List floorlist) {
    this.floorlist = floorlist;
  }

  public Map getIsNowhouseMap() {
    return isNowhouseMap;
  }

  public void setIsNowhouseMap(Map isNowhouseMap) {
    this.isNowhouseMap = isNowhouseMap;
  }

  public List getFloornumlist() {
    return floornumlist;
  }

  public void setFloornumlist(List floornumlist) {
    this.floornumlist = floornumlist;
  }

  public String getBuyhouseorgid() {
    return buyhouseorgid;
  }

  public void setBuyhouseorgid(String buyhouseorgid) {
    this.buyhouseorgid = buyhouseorgid;
  }

  public String getHouseTypehidden() {
    return houseTypehidden;
  }

  public void setHouseTypehidden(String houseTypehidden) {
    this.houseTypehidden = houseTypehidden;
  }

  public String getCoodm() {
    return coodm;
  }

  public void setCoodm(String coodm) {
    this.coodm = coodm;
  }

  public String getTemp_floornum() {
    return temp_floornum;
  }

  public void setTemp_floornum(String temp_floornum) {
    this.temp_floornum = temp_floornum;
  }

  public String getTemp_type_remind() {
    return temp_type_remind;
  }

  public void setTemp_type_remind(String temp_type_remind) {
    this.temp_type_remind = temp_type_remind;
  }

  public String getBanNamehidden() {
    return banNamehidden;
  }

  public void setBanNamehidden(String banNamehidden) {
    this.banNamehidden = banNamehidden;
  }

  public String getIsNeedDel() {
    return isNeedDel;
  }

  public void setIsNeedDel(String isNeedDel) {
    this.isNeedDel = isNeedDel;
  }

  public String getPhotoUrl() {
    return photoUrl;
  }

  public void setPhotoUrl(String photoUrl) {
    this.photoUrl = photoUrl;
  }

  public String getHouseTypetemp() {
    return houseTypetemp;
  }

  public void setHouseTypetemp(String houseTypetemp) {
    this.houseTypetemp = houseTypetemp;
  }

  public String getHiddencheckFloornum() {
    return hiddencheckFloornum;
  }

  public void setHiddencheckFloornum(String hiddencheckFloornum) {
    this.hiddencheckFloornum = hiddencheckFloornum;
  }

  public String getFundBank() {
    return fundBank;
  }

  public void setFundBank(String fundBank) {
    this.fundBank = fundBank;
  }

  public String getFundBankAcc() {
    return fundBankAcc;
  }

  public void setFundBankAcc(String fundBankAcc) {
    this.fundBankAcc = fundBankAcc;
  }

  public String getFloorNumber() {
    return floorNumber;
  }

  public void setFloorNumber(String floorNumber) {
    this.floorNumber = floorNumber;
  }

  public String getSpeAppFlag() {
    return speAppFlag;
  }

  public void setSpeAppFlag(String speAppFlag) {
    this.speAppFlag = speAppFlag;
  }
}