/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.peoplebank.documentstop.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.syscollection.peoplebank.documentstop.bsinterface.IDocumentstopBS;
import org.xpup.hafmis.syscollection.peoplebank.documentstop.form.DocumentstopAF;

/** 
 * MyEclipse Struts
 * Creation date: 02-14-2008
 * 
 * XDoclet definition:
 * @struts.action path="/documentstopNewAC" name="documentstopAF" scope="request" validate="true"
 */
public class DocumentstopNewAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DocumentstopAF documentstopAF = (DocumentstopAF) form;// TODO Auto-generated method stub
    
    try {
      IDocumentstopBS documentstopBS = (IDocumentstopBS) BSUtils
      .getBusinessService("documentstopBS", this, mapping.getModuleConfig());

      SecurityInfo securityInfo=(SecurityInfo)request.getSession().getAttribute("SecurityInfo");
      
      int temp = documentstopBS.countBankInfo();
      
      List temp_list = new ArrayList();
      temp_list.add(documentstopAF.getDataFormatVersion().trim());
      temp_list.add(documentstopAF.getDataReportingAgencies().trim());
      temp_list.add(documentstopAF.getContactPreson().trim());
      temp_list.add(documentstopAF.getContactPhone().trim());
      temp_list.add(documentstopAF.getLocationSpace().trim());
      temp_list.add(documentstopAF.getDataMechanism().trim());
      
      if(temp == 0){
        //²åÈë
        documentstopBS.insertBankInfo(temp_list, securityInfo);
      }else{
        //¸üÐÂ
        documentstopBS.updateBankInfo(temp_list, securityInfo);
      }
      
    } catch (Exception e) {
      e.printStackTrace();
    }
    
		return mapping.findForward("to_forward");
	}
}