/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysfinance.bookmng.datainitialize.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-16-2007
 * Copy Right Information   : 初始数据
 * Project                  : 文件名
 * @Version                 : 1.0
 * @author                  : 张列
 * 生成日期                   : 10-16-2007
 * XDoclet definition:
 * @struts.form name="datainitializeNewAF"
 */
public class DatainitializeNewAF extends ActionForm {

  private static final long serialVersionUID = 1L;

  /** officeName property */
	private String officeName ="";

	/** balanceDirection property */
	private String balanceDirection ="0";
  
	/** credit property */
	private String credit ="0";

	/** subjectCode property */
	private String subjectCode = "";

	/** debit property */
	private String debit = "0";

	/** subjectName property */
	private String subjectName = "";

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the officeName.
	 * @return String
	 */
	public String getOfficeName() {
		return officeName;
	}

	/** 
	 * Set the officeName.
	 * @param officeName The officeName to set
	 */
	public void setOfficeName(String officeName) {
		this.officeName = officeName;
	}

	/** 
	 * Returns the balanceDirection.
	 * @return String
	 */
	public String getBalanceDirection() {
		return balanceDirection;
	}

	/** 
	 * Set the balanceDirection.
	 * @param balanceDirection The balanceDirection to set
	 */
	public void setBalanceDirection(String balanceDirection) {
		this.balanceDirection = balanceDirection;
	}

	/** 
	 * Returns the credit.
	 * @return String
	 */
	public String getCredit() {
		return credit;
	}

	/** 
	 * Set the credit.
	 * @param credit The credit to set
	 */
	public void setCredit(String credit) {
		this.credit = credit;
	}

	/** 
	 * Returns the subjectCode.
	 * @return String
	 */
	public String getSubjectCode() {
		return subjectCode;
	}

	/** 
	 * Set the subjectCode.
	 * @param subjectCode The subjectCode to set
	 */
	public void setSubjectCode(String subjectCode) {
		this.subjectCode = subjectCode;
	}

	/** 
	 * Returns the debit.
	 * @return String
	 */
	public String getDebit() {
		return debit;
	}

	/** 
	 * Set the debit.
	 * @param debit The debit to set
	 */
	public void setDebit(String debit) {
		this.debit = debit;
	}

	/** 
	 * Returns the subjectName.
	 * @return String
	 */
	public String getSubjectName() {
		return subjectName;
	}

	/** 
	 * Set the subjectName.
	 * @param subjectName The subjectName to set
	 */
	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}
}