/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.loanapply.specialapply.action;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.Pagination;
import org.xpup.hafmis.sysloan.loanapply.specialapply.form.SpecialapplyTbAF;

/** 
 * MyEclipse Struts
 * Creation date: 09-29-2007
 * 
 * XDoclet definition:
 * @struts.action path="/specialapplyTbFindAC" name="specialapplyTbAFForm" attribute="specialapplyTbAF" scope="request" validate="true"
 */
public class SpecialapplyTbFindAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
   * 条件查询 准备数据 放在Pagination里
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SpecialapplyTbAF specialapplyTbAF = (SpecialapplyTbAF) form;// TODO Auto-generated method stub
     try {
        HashMap criterions = makeCriterionsMap(specialapplyTbAF);
        Pagination pagination = new Pagination(0, 10, 1, "p2.emp_id", "DESC",
            criterions);
        String paginationKey = SpecialapplyTbShowAC.PAGINATION_KEY;
        request.getSession().setAttribute(paginationKey, pagination);
      } catch (Exception ex) {
        ex.printStackTrace();
      }
      return mapping.findForward("specialapplyTbForwardAC");
    }

    protected HashMap makeCriterionsMap(SpecialapplyTbAF specialapplyTbAF) {
      HashMap map = new HashMap();
      String empId = specialapplyTbAF.getEmpId().trim();
      if (!(empId == null || "".equals(empId))) {
        map.put("empId", empId);
      }
      String borrowerName = specialapplyTbAF.getBorrowerName().trim();
      if (!(borrowerName == null || "".equals(borrowerName))) {
        map.put("borrowerName", borrowerName);
      }
      String cardNum = specialapplyTbAF.getCardNum().trim();
      if (!(cardNum == null || "".equals(cardNum))) {
        map.put("cardNum", cardNum);
      }
      return map;
    }
}