/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.datareadyquery.assistantorg.form;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 09-25-2007 XDoclet definition:
 * 
 * @struts.form name="assistantorgAF"
 */
public class AssistantorgQueryAF extends ActionForm {
  private String assistantOrgName = "";

  private String artfclprsn = "";

  private String assistantType = "";

  private String assistantOrgType = "";
  
  private String inArea = "";

  private Map assistantMap = null;
  
  private Map inAreaMap = null;

  List list = new ArrayList();

  /**
   * 法人代表
   * 
   * @return
   */
  public void setArtfclprsn(String artfclprsn) {
    this.artfclprsn = artfclprsn;
  }

  /**
   * 协作单位名称
   * 
   * @return
   */
  public String getAssistantOrgName() {
    return assistantOrgName;
  }

  /**
   * 协作单位名称
   * 
   * @return
   */
  public void setAssistantOrgName(String assistantOrgName) {
    this.assistantOrgName = assistantOrgName;
  }

  public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
    // TODO Auto-generated method stub
    return null;
  }

  /**
   * Method reset
   * 
   * @param mapping
   * @param request
   */
  public void reset(ActionMapping mapping, HttpServletRequest request) {
    // TODO Auto-generated method stub
    this.artfclprsn = "";
    this.assistantOrgName = "";
    this.assistantOrgType = "";
  }

  /**
   * 协作单位类型
   * 
   * @return
   */
  public String getAssistantOrgType() {
    return assistantOrgType;
  }

  /**
   * 协作单位类型
   * 
   * @return
   */
  public void setAssistantOrgType(String assistantOrgType) {
    this.assistantOrgType = assistantOrgType;
  }

  public Map getAssistantMap() {
    return assistantMap;
  }

  public void setAssistantMap(Map assistantMap) {
    this.assistantMap = assistantMap;
  }

  public List getList() {
    return list;
  }

  public void setList(List list) {
    this.list = list;
  }

  public String getArtfclprsn() {
    return artfclprsn;
  }

  public String getAssistantType() {
    return assistantType;
  }

  public void setAssistantType(String assistantType) {
    this.assistantType = assistantType;
  }

  public String getInArea() {
    return inArea;
  }

  public void setInArea(String inArea) {
    this.inArea = inArea;
  }

  public Map getInAreaMap() {
    return inAreaMap;
  }

  public void setInAreaMap(Map inAreaMap) {
    this.inAreaMap = inAreaMap;
  }

}