/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.loanaccountquery.particulargl.action;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.common.util.Pagination;
import org.xpup.common.util.PaginationUtils;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysloan.loancallback.loancallback.bsinterface.ILoancallbackBS;
import org.xpup.hafmis.sysloan.loancallback.loancallback.dto.ShouldBackListDTO;
import org.xpup.hafmis.sysloan.loancallback.loancallback.form.LoancallbackTaAF;
import org.xpup.hafmis.sysloan.querystatistics.loanaccountquery.particulargl.bsinterface.IParticularglBS;
import org.xpup.hafmis.sysloan.querystatistics.loanaccountquery.particulargl.form.ParticularglTaAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-25-2007
 * 
 * author hanl
 * @struts.action validate="true"
 */
public class ParticularglTaShowAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
  public static final String PAGINATION_KEY = "org.xpup.hafmis.sysloan.querystatistics.loanaccountquery.particulargl.action.ParticularglTaShowAC";
   
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    
    Pagination pagination = getPagination(PAGINATION_KEY, request);
    PaginationUtils.updatePagination(pagination, request);
    IParticularglBS particularglBS = (IParticularglBS) BSUtils.getBusinessService("particularglBS", this, mapping.getModuleConfig());
    ILoancallbackBS loancallbackBS = (ILoancallbackBS) BSUtils.getBusinessService("loancallbackBS", this, mapping.getModuleConfig());
    SecurityInfo securityInfo = (SecurityInfo) request.getSession().getAttribute("SecurityInfo");
    ParticularglTaAF particularglTaAF=new ParticularglTaAF();
    try {
      particularglTaAF=particularglBS.showparticularglList(pagination,securityInfo);
      if(particularglTaAF.getContractid()!=null&&!"".equals(particularglTaAF.getContractid())){
        pagination.getQueryCriterions().put("contractId",particularglTaAF.getContractid());
        LoancallbackTaAF loancallbackTaAF=loancallbackBS.getLoancallbackTaAF(pagination, securityInfo);
        List ll=loancallbackTaAF.getShouldBackList();
        BigDecimal punishinterest=new BigDecimal(0.00);
        for(int j=0;j<ll.size();j++){
          ShouldBackListDTO dto=(ShouldBackListDTO)ll.get(j);
          BigDecimal pi=dto.getPunishInterest();
          punishinterest=punishinterest.add(pi);
        }
        particularglTaAF.setOwepunishinterest(punishinterest.toString());
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
    
    
    request.setAttribute("particularglTaAF",particularglTaAF);
    request.getSession().setAttribute("toprintparticularglTaAF",particularglTaAF);
		return mapping.findForward("particulargl_ta_show");
	}
  
   private Pagination getPagination(String paginationKey,HttpServletRequest request) {
      Pagination pagination = (Pagination) request.getSession().getAttribute(
          paginationKey);
      if (pagination == null) {
        pagination = new Pagination(0, 10, 1, " substr(pl202.biz_date, 0, 4) ", "DESC", new HashMap(0));
        request.getSession().setAttribute(paginationKey, pagination);
      }
      return pagination;
    }
}