/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.loanaccountquery.particulargl.action;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.Pagination;
import org.xpup.hafmis.sysloan.querystatistics.loanaccountquery.particulargl.form.ParticularglTaAF;
/** 
 * MyEclipse Struts
 * Creation date: 10-25-2007
 * author hanl
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ParticularglTaFindAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    ParticularglTaAF particularglTaAF=(ParticularglTaAF)form;
    HashMap criterions = makeCriterionsMap(particularglTaAF);
    Pagination pagination = new Pagination(0, 10, 1, " substr(pl202.biz_date, 0, 4) ", "DESC",criterions);
    String paginationKey = ParticularglTaShowAC.PAGINATION_KEY;
    request.getSession().setAttribute(paginationKey, pagination);
    return mapping.findForward("particularglTaShowAC");
  }

  protected HashMap makeCriterionsMap(ParticularglTaAF particularglTaAF) {
  HashMap map = new HashMap();
  String borrowercontractid =particularglTaAF.getBorrowercontractid().trim();
  if (!(borrowercontractid == null || "".equals(borrowercontractid.trim()))) {
    map.put("borrowercontractid",borrowercontractid );
  }
  String bizdateB =particularglTaAF.getBizdateB().trim();
  if (!(bizdateB == null || "".equals(bizdateB.trim()))) {
    map.put("bizdateB", bizdateB);
  }
  String bizdateE =particularglTaAF.getBizdateE().trim();
  if (!(bizdateE == null || "".equals(bizdateE.trim()))) {
    map.put("bizdateE",bizdateE);
  }
  
  return map;
  }
}