/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.paymng.agent.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-19-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AgentInfoQueryForWardAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
    HttpSession session = request.getSession();
    session.setAttribute(AgentInfoQueryTaShowAC.PAGINATION_KEY, null);
    session.setAttribute(AgentInfoQueryTbShowAC.PAGINATION_KEY, null);
    session.setAttribute(AgentInfoQueryTcShowAC.PAGINATION_KEY, null);
    session.setAttribute("payId_num_session", null);
    session.setAttribute("orgId_num_session", null);
		return mapping.findForward("agentInfoQueryTaShowAC");
	}
}