/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.paymng.agent.action;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.xpup.hafmis.common.form.IdAF;

/** 
 * MyEclipse Struts
 * Creation date: 12-19-2007
 * 
 * XDoclet definition:
 * @struts.action path="/agentInfoQueryTaModifyAC" name="idAF" scope="request" validate="true"
 */
public class AgentInfoQueryTaModifyAC extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward queryOrgInfo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		IdAF idAF = (IdAF) form;// TODO Auto-generated method stub
    request.setAttribute("payId_num", idAF.getId().toString());
		return mapping.findForward("agentInfoQueryTbShowAC");
	}
}