/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.paymng.agent.action;

import java.util.HashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.common.util.Pagination;
import org.xpup.common.util.PaginationUtils;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.syscollection.paymng.agent.bsinterface.IAgentBS;
import org.xpup.hafmis.syscollection.paymng.agent.form.AgentInfoQueryTaAF;

/** 
 * MyEclipse Struts
 * Creation date: 12-19-2007
 * 
 * XDoclet definition:
 * @struts.action path="/agentInfoQueryTaShowAC" name="idAF" scope="request" validate="true"
 */
public class AgentInfoQueryTaShowAC extends Action {
	/*
	 * Generated Methods
	 */

  public static final String PAGINATION_KEY = "org.xpup.hafmis.syscollection.paymng.agent.action.AgentInfoQueryTaShowAC";
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//IdAF idAF = (IdAF) form;// TODO Auto-generated method stub
    try {
      IAgentBS agentBS = (IAgentBS) BSUtils.getBusinessService("agentBS", this,
          mapping.getModuleConfig());
      SecurityInfo securityInfo = (SecurityInfo) request.getSession()
      .getAttribute("SecurityInfo");
      Pagination pagination = getPagination(PAGINATION_KEY, request);
      PaginationUtils.updatePagination(pagination, request);
      List list = agentBS.queryAgentInfoTaList(pagination,securityInfo);
      int count = agentBS.queryAgentInfoTaListCount(pagination,securityInfo);
      pagination.setNrOfElements(count);
      AgentInfoQueryTaAF agentInfoQueryTaAF = new AgentInfoQueryTaAF();
      agentInfoQueryTaAF.setList(list);
      request.setAttribute("agentInfoQueryTaAF", agentInfoQueryTaAF);
    } catch (Exception e) {
      e.printStackTrace();
    }
		return mapping.findForward("to_agentInfoQueryTa_show");
	}
  
  private Pagination getPagination(String paginationKey,
      HttpServletRequest request) {
    Pagination pagination = (Pagination) request.getSession().getAttribute(
        paginationKey);
    if (pagination == null) {
      pagination = new Pagination(0, 10, 1, "a301.financial_pay_id", "ASC", new HashMap(0));
      request.getSession().setAttribute(paginationKey, pagination);
    }
    return pagination;
  }
}