/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.paymng.agent.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 12-20-2007
 * 
 * XDoclet definition:
 * @struts.action path="/agentInfoQueryTcModifyAC" name="idAF" parameter="method" scope="request" validate="true"
 */
public class AgentInfoQueryTcModifyAC extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward queryBack(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//IdAF idAF = (IdAF) form;// TODO Auto-generated method stub
    HttpSession session = request.getSession();
    session.setAttribute(AgentInfoQueryTcShowAC.PAGINATION_KEY, null);
    session.setAttribute("orgId_num_session", null);
    return mapping.findForward("agentInfoQueryTbShowAC");
	}
}