/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.pickupmng.pickup.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-23-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class TransactionActionAC extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    request.getSession().removeAttribute(PickupShowAC.PAGINACTION_KEY);
//    System.out.println("经过普通提取的ForwardAction");
    request.getSession().removeAttribute("orgId");
    request.getSession().removeAttribute("liwenhao");
    request.getSession().removeAttribute("employeeInfo");
    request.getSession().removeAttribute("special");
    request.getSession().removeAttribute("display");
   
		return new ActionForward("/pickupShowAC.do");
	}
}