/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.dataready.develop.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.xpup.hafmis.common.form.IdAF;
import org.xpup.hafmis.sysloan.common.domain.entity.Build;

/** 
 * MyEclipse Struts
 * Creation date: 06-23-2008
 * 
 * XDoclet definition:
 * @struts.form name="buildMainTainAF"
 */
public class BuildMainTainAF extends IdAF {
	/*
	 * Generated Methods
	 */

	/**
   * 
   */
  private static final long serialVersionUID = 1L;
  
  private Build build = new Build();
  private List list = new ArrayList();
  private String developName = "";

  /** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

  public Build getBuild() {
    return build;
  }

  public void setBuild(Build build) {
    this.build = build;
  }

  public String getDevelopName() {
    return developName;
  }

  public void setDevelopName(String developName) {
    this.developName = developName;
  }

  public List getList() {
    return list;
  }

  public void setList(List list) {
    this.list = list;
  }
}