/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.pickupmng.pickup.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.xpup.hafmis.common.form.IdAF;
import org.xpup.hafmis.syscollection.common.domain.entity.PickTail;

/** 
 * MyEclipse Struts
 * Creation date: 06-28-2007
 * XDoclet definition:
 * @struts.form name="pickupMaintainAF"
 * @author¿ÓŒƒ∫∆
 */
public class PickupMaintainAF extends IdAF {
  private String noteNumber;
  private String result;
  private String tailHeadId;
  private String other_card_num="";
  private String houseNum="";
  
	public String getOther_card_num() {
    return other_card_num;
  }
  public void setOther_card_num(String other_card_num) {
    this.other_card_num = other_card_num;
  }
  public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		return null;
	}
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}
  public String getResult() {
    return result;
  }
  public void setResult(String result) {
    this.result = result;
  }
  public String getNoteNumber() {
    return noteNumber;
  }
  public void setNoteNumber(String noteNumber) {
    this.noteNumber = noteNumber;
  }
  public String getTailHeadId() {
    return tailHeadId;
  }
  public void setTailHeadId(String tailHeadId) {
    this.tailHeadId = tailHeadId;
  }
  public String getHouseNum() {
    return houseNum;
  }
  public void setHouseNum(String houseNum) {
    this.houseNum = houseNum;
  }
}