/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.pickupmng.pickup.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-06-2007
 * 李文浩..添加的Form
 * XDoclet definition:
 * @struts.form name="pickupADDAF"
 */
public class PickupAddAF extends ActionForm {
  private String maxPickBalance;
  private String distoryInterest;
  private String sum;
  private String noteNumber;
  private String reason;
  private String type;
  private String orgId;
  private String empId;
  private String curBalance;
  private String preBalance;
  private String curInterest;
  private String preInterest;
  private String pickBalance;
  private String houseNum="";
  
  private String other_card_num="";
	public String getOther_card_num() {
    return other_card_num;
  }

  public void setOther_card_num(String other_card_num) {
    this.other_card_num = other_card_num;
  }

  /** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getCurBalance() {
    return curBalance;
  }

  public void setCurBalance(String curBalance) {
    this.curBalance = curBalance;
  }

  public String getCurInterest() {
    return curInterest;
  }

  public void setCurInterest(String curInterest) {
    this.curInterest = curInterest;
  }

  public String getEmpId() {
    return empId;
  }

  public void setEmpId(String empId) {
    this.empId = empId;
  }

  public String getPreBalance() {
    return preBalance;
  }

  public void setPreBalance(String preBalance) {
    this.preBalance = preBalance;
  }

  public String getPreInterest() {
    return preInterest;
  }

  public void setPreInterest(String preInterest) {
    this.preInterest = preInterest;
  }

  public String getPickBalance() {
    return pickBalance;
  }

  public void setPickBalance(String pickBalance) {
    this.pickBalance = pickBalance;
  }

  public String getDistoryInterest() {
    return distoryInterest;
  }

  public void setDistoryInterest(String distoryInterest) {
    this.distoryInterest = distoryInterest;
  }

  public String getMaxPickBalance() {
    return maxPickBalance;
  }

  public void setMaxPickBalance(String maxPickBalance) {
    this.maxPickBalance = maxPickBalance;
  }

  public String getSum() {
    return sum;
  }

  public void setSum(String sum) {
    this.sum = sum;
  }

  public String getNoteNumber() {
    return noteNumber;
  }

  public void setNoteNumber(String noteNumber) {
    this.noteNumber = noteNumber;
  }

  public String getOrgId() {
    return orgId;
  }

  public void setOrgId(String orgId) {
    this.orgId = orgId;
  }

  public String getHouseNum() {
    return houseNum;
  }

  public void setHouseNum(String houseNum) {
    this.houseNum = houseNum;
  }
}