/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.pickupmng.pickup.form;

import java.math.BigDecimal;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.xpup.hafmis.syscollection.common.domain.entity.PickTail;

/** 
 * MyEclipse Struts
 * Creation date: 06-28-2007
 * 
 * XDoclet definition:
 * @struts.form name="pickupGetCompanyIdAF"
 */
public class PickupGetCompanyIdAF extends ActionForm {
  private String id;
  private String name;
  private List list;
  private String buttonState;
  private String docNumber;
  private String noteNumber;
//  部分提取人数：1 销户提取人数：1 提取总人数：2 提取金额：2000 销户利息：100 提取总金额：4100
  private int somePickupNumber;
  private int distoryPickupNumber;
  private int sumPerson;
  private BigDecimal sumBalance = new BigDecimal(0.00);
  private BigDecimal sumInterese = new BigDecimal(0.00);
  private BigDecimal sumTotal = new BigDecimal(0.00);
 private String counts;
 private String versionflag="0";//版本标识：0：无信息；1：未提交；2：已提交
 
 private String other_card_num="";
  public String getOther_card_num() {
  return other_card_num;
}

public void setOther_card_num(String other_card_num) {
  this.other_card_num = other_card_num;
}

  public String getVersionflag() {
  return versionflag;
}

public void setVersionflag(String versionflag) {
  this.versionflag = versionflag;
}

  public String getCounts() {
    return counts;
  }

  public void setCounts(String counts) {
    this.counts = counts;
  }
  public ActionErrors validate(ActionMapping mapping,
      HttpServletRequest request) {
    // TODO Auto-generated method stub
    return null;
  }

  /** 
   * Method reset
   * @param mapping
   * @param request
   */
  public void reset(ActionMapping mapping, HttpServletRequest request) {
    // TODO Auto-generated method stub
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public List getList() {
    return list;
  }

  public void setList(List list) {
    this.list = list;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getNoteNumber() {
    return noteNumber;
  }

  public void setNoteNumber(String noteNumber) {
    this.noteNumber = noteNumber;
  }

  public int getDistoryPickupNumber() {
    return distoryPickupNumber;
  }

  public void setDistoryPickupNumber(int distoryPickupNumber) {
    this.distoryPickupNumber = distoryPickupNumber;
  }

  public int getSomePickupNumber() {
    return somePickupNumber;
  }

  public void setSomePickupNumber(int somePickupNumber) {
    this.somePickupNumber = somePickupNumber;
  }
  public void setSumPerson(int sumPerson) {
    this.sumPerson = sumPerson;
  }

  public BigDecimal getSumBalance() {
    return sumBalance.setScale(2);
  }

  public void setSumBalance(BigDecimal sumBalance) {
    this.sumBalance = sumBalance;
  }

  public BigDecimal getSumInterese() {
    return sumInterese.setScale(2);
  }

  public void setSumInterese(BigDecimal sumInterese) {
    this.sumInterese = sumInterese;
  }

  public BigDecimal getSumTotal() {
    return sumTotal.setScale(2);
  }

  public void setSumTotal(BigDecimal sumTotal) {
    this.sumTotal = sumTotal;
  }

  public int getSumPerson() {
    return sumPerson;
  }

  public String getDocNumber() {
    return docNumber;
  }

  public void setDocNumber(String docNumber) {
    this.docNumber = docNumber;
  }

  public String getButtonState() {
    return buttonState;
  }

  public void setButtonState(String buttonState) {
    this.buttonState = buttonState;
  }
}