/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.dataready.assistantorg.action;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.LookupDispatchAction;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysloan.dataready.assistantorg.bsinterface.IAssistantorgBS;
import org.xpup.hafmis.sysloan.dataready.assistantorg.dto.AssistantorgAFDTO;
import org.xpup.hafmis.sysloan.dataready.assistantorg.form.AssistantorgAF;

/** 
 * MyEclipse Struts
 * Creation date: 09-25-2007
 * 
 * XDoclet definition:
 * @struts.action path="/assistantorgAddUpdateAC" name="assistantorgAF" scope="request" validate="true"
 */
public class AssistantorgAddUpdateAC extends LookupDispatchAction {
  protected Map getKeyMethodMap() {
    Map map = new HashMap();
    map.put("button.sure", "sure");
    map.put("button.scan", "scan");
    map.put("button.back", "back");
    return map;
  }
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward sure(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    ActionMessages message=null;
		AssistantorgAF AF = (AssistantorgAF) form;
    
    AssistantorgAFDTO assistantorgDTO = null;
    
    SecurityInfo securityInfo = (SecurityInfo) request.getSession()
    .getAttribute("SecurityInfo");
    String error="操作失败!";
    try{
      IAssistantorgBS assistantorgBS=(IAssistantorgBS)BSUtils
      .getBusinessService("assistantorgBS", this, mapping.getModuleConfig());
      if(AF.getType().equals("添加"))
      {
        
        //张列改 头
        assistantorgDTO = new AssistantorgAFDTO();
        BeanUtils.copyProperties(assistantorgDTO, AF);
        assistantorgBS.insertAssistantorgList(assistantorgDTO,securityInfo);
        //张列改 尾
        
        error="添加成功!";
        return mapping.findForward("assistantorgShowAC"); //添加成功
      }
      if(AF.getType().equals("修改"))
      {  
        
        //张列改 头
        assistantorgDTO = new AssistantorgAFDTO();
        BeanUtils.copyProperties(assistantorgDTO, AF);
        assistantorgBS.updateAssistantOrg(assistantorgDTO,securityInfo);
        //张列改 尾
        
        error="修改成功!";
        return mapping.findForward("assistantorgShowAC");
      }
    }
    catch(Exception e)
    {
      error="操作失败";
      e.printStackTrace();  
    }finally{
      message= new ActionMessages();
      message.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(error,false));
      saveErrors(request,message);
    }
    return mapping.findForward("assistantorgShowAC"); //添加成功
	}
  
  public ActionForward scan(ActionMapping mapping, ActionForm form,      
      HttpServletRequest request, HttpServletResponse response) {
//    ActionMessages message=null;
//    AssistantorgAF AF = (AssistantorgAF) form;
//    SecurityInfo securityInfo = (SecurityInfo) request.getSession()
//    .getAttribute("SecurityInfo");
//    try{
//      IAssistantorgBS assistantorgBS=(IAssistantorgBS)BSUtils
//      .getBusinessService("assistantorgBS", this, mapping.getModuleConfig());
//      if(AF.getType().equals("添加"))
//      {
//        assistantorgBS.insertAssistantorgList(AF,securityInfo);
//        return mapping.findForward("assistantorgShowAC"); //添加成功
//      }
//      if(AF.getType().equals("修改"))
//      {  
//        assistantorgBS.updateAssistantOrg(AF,securityInfo);
//        return mapping.findForward("assistantorgShowAC");
//      }
//    }
//    catch(Exception e)
//    {
//      message= new ActionMessages();
//      message.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage("操作失败",false));
//      saveErrors(request,message);
//      e.printStackTrace();
//      return mapping.findForward("to_assistantorg_addupdate");   
//    }
    return mapping.findForward("assistantorgShowAC"); //添加成功
  }
  public ActionForward back(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {
    return mapping.findForward("assistantorgShowAC");
  }
}