/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.dataready.assistantorg.action;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.common.util.Pagination;
import org.xpup.common.util.PaginationUtils;
import org.xpup.hafmis.sysloan.dataready.assistantorg.bsinterface.IInsuranceBS;
import org.xpup.hafmis.sysloan.dataready.assistantorg.form.AssistantorgShowListAF;

/** 
 * MyEclipse Struts
 * Creation date: 09-28-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class InsuranceShowAC extends Action {
  
  public static final String PAGINATION_KEY =
    "org.xpup.hafmis.sysloan.dataready.assistantorg.action.InsuranceShowAC";
  public ActionForward execute(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {
    AssistantorgShowListAF assistantorgShowListAF=new AssistantorgShowListAF();
    try{
      Pagination pagination = getPagination(PAGINATION_KEY, request);
      PaginationUtils.updatePagination(pagination, request);
      IInsuranceBS insuranceBS=(IInsuranceBS)BSUtils
      .getBusinessService("insuranceBS", this, mapping.getModuleConfig());
      assistantorgShowListAF.setList(insuranceBS.findInsuranceList(pagination));
    }
    catch(Exception e)
    {
      e.printStackTrace();
    }
    request.setAttribute("ListAF", assistantorgShowListAF);
    return mapping.findForward("to_insurance_show");
  }
  
  private Pagination getPagination(String paginationKey,    //需要改动 字符 排序
      HttpServletRequest request) {
    Pagination pagination = (Pagination) request.getSession().getAttribute(
        paginationKey);
    if (pagination == null) {   
      pagination = new Pagination(0, 10, 1, "assistantOrg.assistantOrgId ", "DESC",
          new HashMap(0));
      request.getSession().setAttribute(PAGINATION_KEY, pagination);
    }

    return pagination;
  }
}