/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.querystatistics.loandeskaccquery.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysloan.querystatistics.querystatistics.loandeskaccquery.dto.LoandeskaccqueryTbDTO;
import org.xpup.hafmis.sysloan.querystatistics.querystatistics.loandeskaccquery.form.LoanDeskaccQueryTbAF;

/**
 * MyEclipse Struts Creation date: 10-22-2007 XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class LoanDeskaccQueryTbPrintAC extends Action {
  /*
   * Generated Methods
   */

  /**
   * Method execute
   * 
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   */
  public ActionForward execute(ActionMapping mapping, ActionForm form,
      HttpServletRequest request, HttpServletResponse response) {
    LoanDeskaccQueryTbAF loanDeskaccQueryTbAF = (LoanDeskaccQueryTbAF) request
        .getSession().getAttribute("loanDeskaccQueryTbAFAlllist");
    if (loanDeskaccQueryTbAF.getOverplusloanmoney() == null) {
      loanDeskaccQueryTbAF.setOverplusloanmoney("0");
    }
    if (loanDeskaccQueryTbAF.getNobackmoney() == null) {
      loanDeskaccQueryTbAF.setNobackmoney("0");
    }
    if (loanDeskaccQueryTbAF.getOverplusloanmoney() == null) {
      loanDeskaccQueryTbAF.setOverplusloanmoney("0");
    }
    if (loanDeskaccQueryTbAF.getBallbalance() == null) {
      loanDeskaccQueryTbAF.setBallbalance("0");
    }
    if (loanDeskaccQueryTbAF.getSrealcorpus() == null) {
      loanDeskaccQueryTbAF.setSrealcorpus("0");
    }
    if (loanDeskaccQueryTbAF.getSrealinterest() == null) {
      loanDeskaccQueryTbAF.setSrealinterest("0");
    }
    if (loanDeskaccQueryTbAF.getSrealpunishinterest() == null) {
      loanDeskaccQueryTbAF.setSrealpunishinterest("0");
    }
    if (loanDeskaccQueryTbAF.getOwercorpus() == null) {
      loanDeskaccQueryTbAF.setOwercorpus("0");
    }
    if (loanDeskaccQueryTbAF.getOweinterest() == null) {
      loanDeskaccQueryTbAF.setOweinterest("0");
    }
    if (loanDeskaccQueryTbAF.getOwepunishinterest() == null) {
      loanDeskaccQueryTbAF.setOwepunishinterest("0");
    }
    List tempalllist = loanDeskaccQueryTbAF.getAlllist();

    for (int i = 0; i < tempalllist.size(); i++) {
      LoandeskaccqueryTbDTO loandeskaccqueryTbDTO = (LoandeskaccqueryTbDTO) tempalllist
          .get(i);
      if (loandeskaccqueryTbDTO.getAccordmoney() == null
          || "".equals(loandeskaccqueryTbDTO.getAccordmoney())) {
        loandeskaccqueryTbDTO.setAccordmoney("0");
      }
      if (loandeskaccqueryTbDTO.getOverloanmoney() == null
          || "".equals(loandeskaccqueryTbDTO.getOverloanmoney())) {
        loandeskaccqueryTbDTO.setOverloanmoney("0");

      }
      if (loandeskaccqueryTbDTO.getBaddebtmoney() == null
          || "".equals(loandeskaccqueryTbDTO.getBaddebtmoney())) {
        loandeskaccqueryTbDTO.setBaddebtmoney("0");
      }
      if (loandeskaccqueryTbDTO.getBailmoney() == null
          || "".equals(loandeskaccqueryTbDTO.getBailmoney())) {
        loandeskaccqueryTbDTO.setBailmoney("0");
      }
      if (loandeskaccqueryTbDTO.getShouldcorpus() == null
          || "".equals(loandeskaccqueryTbDTO.getShouldcorpus())) {
        loandeskaccqueryTbDTO.setShouldcorpus("0");
      }
      if (loandeskaccqueryTbDTO.getShouldinterest() == null
          || "".equals(loandeskaccqueryTbDTO.getShouldcorpus())) {
        loandeskaccqueryTbDTO.setShouldinterest("0");
      }
      if (loandeskaccqueryTbDTO.getShouldpunishinterest() == null
          || "".equals(loandeskaccqueryTbDTO.getShouldpunishinterest())) {
        loandeskaccqueryTbDTO.setShouldpunishinterest("0");
      }
      if (loandeskaccqueryTbDTO.getRealcorpus() == null
          || "".equals(loandeskaccqueryTbDTO.getRealcorpus())) {
        loandeskaccqueryTbDTO.setRealcorpus("0");
      }
      if (loandeskaccqueryTbDTO.getRealinterest() == null
          || "".equals(loandeskaccqueryTbDTO.getRealcorpus())) {
        loandeskaccqueryTbDTO.setRealinterest("0");
      }
      if (loandeskaccqueryTbDTO.getRealpunishinterest() == null
          || "".equals(loandeskaccqueryTbDTO.getRealpunishinterest())) {
        loandeskaccqueryTbDTO.setRealpunishinterest("0");
      }
    }
    loanDeskaccQueryTbAF.setAlllist(tempalllist);
    request.setAttribute("loanDeskaccQueryTbAF", loanDeskaccQueryTbAF);
    SecurityInfo securityInfo = (SecurityInfo) request.getSession()
        .getAttribute("SecurityInfo");
    String opertname = securityInfo.getRealName();
    String time = securityInfo.getUserInfo().getPlbizDate();
    request.setAttribute("opertname", opertname);
    request.setAttribute("time", time);
    request.getSession().setAttribute("loanDeskaccQueryTbAFAlllist", null);

    return mapping.findForward("loandeskaccquerytb_cell");
  }
}