/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysfinance.bookmng.datainitialize.action;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.orgstrct.dto.OfficeDto;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysfinance.bookmng.datainitialize.bsinterface.IDatainitializeBS;
import org.xpup.hafmis.sysfinance.bookmng.datainitialize.form.DatainitializeNewAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-16-2007
 * Copy Right Information   : 初始数据
 * Project                  : 文件名
 * @Version                 : 1.0
 * @author                  : 张列
 * 生成日期                   : 10-16-2007
 * XDoclet definition:
 * @struts.action validate="true"
 * 张列 得到初始数据信息
 */
public class DatainitalizeShowAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    List officeList1 = null;
    //办事处放进 officeList 集合里
    try {
      //权限
      SecurityInfo securityInfo = (SecurityInfo) request.getSession()
      .getAttribute("SecurityInfo");
      // 取出用户权限办事处,显示在下拉菜单中
      List officeList = securityInfo.getOfficeList();
      officeList1 = new ArrayList();
      OfficeDto officedto = null;
      Iterator itr1 = officeList.iterator();
      while (itr1.hasNext()) {
        officedto = (OfficeDto) itr1.next();
        officeList1.add(new org.apache.struts.util.LabelValueBean(officedto
            .getOfficeName(), officedto.getOfficeCode()));
      }
      request.setAttribute("officeList1", officeList1);
      
      IDatainitializeBS datainitializeBS = (IDatainitializeBS) BSUtils.getBusinessService(
          "datainitializeBS", this, mapping.getModuleConfig());
      //权限拿出BOOKID
      String bookId = securityInfo.getBookId();
      //获得OFFICE
      if(request.getParameter("status")==null&&request.getAttribute("status")==null){
        if(request.getAttribute("debitError")!=null){
          DatainitializeNewAF datainitializeNewAF = new DatainitializeNewAF();
          datainitializeNewAF.setOfficeName((String)request.getAttribute("officeName"));
          request.setAttribute("datainitializeNewAF", datainitializeNewAF);
          request.setAttribute("datainitializeLists", request.getAttribute("datainitializeLists"));
        }else{
            //获得科目代码和科目名称
            List lendsMoneyLists = datainitializeBS.getLendsMoney(bookId, "");
            if(request.getAttribute("true") != null){
              DatainitializeNewAF datainitializeNewAF = new DatainitializeNewAF();
              request.setAttribute("datainitializeNewAF", datainitializeNewAF);
            }
            request.setAttribute("datainitializeLists", lendsMoneyLists);
        }
      }else{
        //获得累计借方和累计贷方
        if(request.getAttribute("totals")!=null){
          request.setAttribute("datainitializeLists", request.getAttribute("totals_datainitializeDTO"));
        }else{
          String officeName = request.getParameter("officecode");
          List lendsMoneyLists = datainitializeBS.getLendsMoney(bookId, officeName);
          request.setAttribute("datainitializeLists", lendsMoneyLists);
          DatainitializeNewAF datainitializeNewAF = new DatainitializeNewAF();
          datainitializeNewAF.setOfficeName(officeName);
          request.setAttribute("datainitializeNewAF", datainitializeNewAF);
        }
      }
      //判断FN101.BOOK_ST，如果为0，全部按钮可用；如果为1，全部按钮禁用。
      String bookST = datainitializeBS.getBookST(bookId);
      if(bookST.equals("0")){
        request.setAttribute("bookST", "0");
      }
      
    } catch (Exception e) {
      e.printStackTrace();
    }
		return mapping.findForward("to_datainitialize_new");
	}
}