/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.collloanbackcheck.form;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;


public class CollLoanbackcheckAF extends ActionForm {
  
  private static final long serialVersionUID = 1L;

  private String officeCode="";
  private String collectionBankId="";
  private String bizStatus="";
  private String batch_num="";
  private String startDate="";
  private String endDate="";
  private String type="";
  private String flag="";
  private Map map = null;
  
  private int totalCount; //总发生人数
  private BigDecimal totalInterest = new BigDecimal(0);//利息
  private BigDecimal totalDcitsum = new BigDecimal(0);//总发生金额

  private String statusType="";//判断按钮禁用
  
  private String orgid="";
  private String orgname="";
  private String empid="";
  private String empname="";
  private List list;
  
  public String getBatch_num() {
    return batch_num;
  }
  public void setBatch_num(String batch_num) {
    this.batch_num = batch_num;
  }
 
  public String getBizStatus() {
    return bizStatus;
  }
  public void setBizStatus(String bizStatus) {
    this.bizStatus = bizStatus;
  }
  public String getCollectionBankId() {
    return collectionBankId;
  }
  public void setCollectionBankId(String collectionBankId) {
    this.collectionBankId = collectionBankId;
  }
  public List getList() {
    return list;
  }
  public void setList(List list) {
    this.list = list;
  }
  public String getOfficeCode() {
    return officeCode;
  }
  public void setOfficeCode(String officeCode) {
    this.officeCode = officeCode;
  }
  public int getTotalCount() {
    return totalCount;
  }
  public void setTotalCount(int totalCount) {
    this.totalCount = totalCount;
  }
  public BigDecimal getTotalDcitsum() {
    return totalDcitsum;
  }
  public void setTotalDcitsum(BigDecimal totalDcitsum) {
    this.totalDcitsum = totalDcitsum;
  }
  public BigDecimal getTotalInterest() {
    return totalInterest;
  }
  public void setTotalInterest(BigDecimal totalInterest) {
    this.totalInterest = totalInterest;
  }
  public String getStartDate() {
    return startDate;
  }
  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }
  public String getEndDate() {
    return endDate;
  }
  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }
  public Map getMap() {
    return map;
  }
  public void setMap(Map map) {
    this.map = map;
  }
  public String getStatusType() {
    return statusType;
  }
  public void setStatusType(String statusType) {
    this.statusType = statusType;
  }
  public String getEmpid() {
    return empid;
  }
  public void setEmpid(String empid) {
    this.empid = empid;
  }
  public String getEmpname() {
    return empname;
  }
  public void setEmpname(String empname) {
    this.empname = empname;
  }
  public String getOrgid() {
    return orgid;
  }
  public void setOrgid(String orgid) {
    this.orgid = orgid;
  }
  public String getOrgname() {
    return orgname;
  }
  public void setOrgname(String orgname) {
    this.orgname = orgname;
  }
  public String getFlag() {
    return flag;
  }
  public void setFlag(String flag) {
    this.flag = flag;
  }
  
}