/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.paymng.agent.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-19-2007
 * 
 * XDoclet definition:
 * @struts.form name="agentInfoQueryTbAF"
 */
public class AgentInfoQueryTbAF extends ActionForm {
	/*
	 * Generated fields
	 */

  private static final long serialVersionUID = 1L;

  /** orgId property */
	private String orgId = "";

	/** orgAgentNum property */
	private String orgAgentNum = "";

	/** payMonth property */
	private String payMonth = "";

	/** orgName property */
	private String orgName = "";

  private List list = new ArrayList();
	/*
	 * Generated Methods
	 */

	public List getList() {
    return list;
  }

  public void setList(List list) {
    this.list = list;
  }

  /** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the orgId.
	 * @return String
	 */
	public String getOrgId() {
		return orgId;
	}

	/** 
	 * Set the orgId.
	 * @param orgId The orgId to set
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	/** 
	 * Returns the orgAgentNum.
	 * @return String
	 */
	public String getOrgAgentNum() {
		return orgAgentNum;
	}

	/** 
	 * Set the orgAgentNum.
	 * @param orgAgentNum The orgAgentNum to set
	 */
	public void setOrgAgentNum(String orgAgentNum) {
		this.orgAgentNum = orgAgentNum;
	}

	/** 
	 * Returns the payMonth.
	 * @return String
	 */
	public String getPayMonth() {
		return payMonth;
	}

	/** 
	 * Set the payMonth.
	 * @param payMonth The payMonth to set
	 */
	public void setPayMonth(String payMonth) {
		this.payMonth = payMonth;
	}

	/** 
	 * Returns the orgName.
	 * @return String
	 */
	public String getOrgName() {
		return orgName;
	}

	/** 
	 * Set the orgName.
	 * @param orgName The orgName to set
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
}