/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.querystatistics.baseinfosearch.modifyaccount.action;
import java.util.HashMap;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.common.util.Pagination;
import org.xpup.common.util.PaginationUtils;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.syscollection.querystatistics.baseinfosearch.modifyaccount.bsinterface.IModifyBS;
import org.xpup.hafmis.syscollection.querystatistics.baseinfosearch.modifyaccount.form.OpenMondifyInfoAF;
public class ShowOpenMondifyListAC extends Action {
  public static final String SHOWOPENMONDIFY_KEY = "org.xpup.hafmis.syscollection.querystatistics.baseinfosearch.modifyaccount.action.ShowOpenMondifyListAC";
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    try{
      IModifyBS open = (IModifyBS)BSUtils.getBusinessService("modifyBS",this,mapping.getModuleConfig());
      Pagination pag = (Pagination)request.getSession().getAttribute(SHOWOPENMONDIFY_KEY);
      OpenMondifyInfoAF af = new OpenMondifyInfoAF();
      if(pag == null){//证明是第一次进来...所以null;
        pag = getPagination(SHOWOPENMONDIFY_KEY,request);
        request.getSession().setAttribute("updateInfo", af);
      }else{
        PaginationUtils.updatePagination(pag, request);
        SecurityInfo securityInfo = (SecurityInfo) request.getSession().getAttribute("SecurityInfo");
        List list = open.getOpenMondifyInfoList(pag,securityInfo);
        List printList = open.getOpenMondifyInfoList_YG(pag, securityInfo);
//        List printList = open.getPrintInfo(pag, securityInfo);
        if(!list.isEmpty())
          af.setButtonState("显示打印");
        af.setList(list);
        request.getSession().setAttribute("print", printList);//把打印的数据放在Session里
        request.getSession().setAttribute("updateInfo", af);
      }
    }catch(Exception s){
      s.printStackTrace();
    }
		return new ActionForward("/openMondifyInfoList.jsp");
	}
   private Pagination getPagination(String paginationKey,HttpServletRequest request) {
      Pagination pagination = (Pagination) request.getSession().getAttribute(paginationKey);
      if (pagination == null) {
        pagination = new Pagination(0, 10, 1, "b.org.id","DESC",new HashMap(0));
        request.getSession().setAttribute(paginationKey, pagination);
      }   
      return pagination;
    }
}