/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysloan.querystatistics.querystatistics.loandeskaccquery.form;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-22-2007
 * 
 * XDoclet definition:
 * @struts.form name="LoanDeskaccQueryTbAF"
 */
public class LoanDeskaccQueryTbAF extends ActionForm {


  private String docnum;//凭证编号
  private String biztype;// 业务类型  
  private Map biztypeMap=new HashMap();
  private String bizdateB;// 业务日期起
  private String bizdateE;// 业务日期至
  
  private String contractid;//合同编号
  private String loankouacc;//贷款账号
  private String borrowername;//借款人姓名
  private String cardnum;//证件号码   
  private String loanbank;//放款银行    
  private String loanmoney;// 贷款金额   
  private String loanlimit;//贷款期限
  private String loanmode;//还款方式
  private String overplusloanmoney;//贷款余额
  private String nobackmoney;//呆账未回收金额
  private String oveaerloanrepay;//挂账余额
  private String ballbalance;//保证金余额
  private String srealcorpus;//总还本金
  private String srealinterest;//总还利息
  private String srealpunishinterest;//总还罚息利息
  private String owercorpus;//欠还本金
  private String oweinterest;//欠还利息
  private String owepunishinterest;//欠还罚息利息
    
  //总计 总发放金额 总挂账金额 总呆账核销金额 总保证金 总实还本金 总实还利息 总实还罚息 总回收金额
  private String tolaccordmoney;
  private String toloverloanmoney;
  private String tolbaddebtmoney;
  private String tolbailmoney;
  private String tolrealcorpus;
  private String tolrealinterest;
  private String tolrealpunishinterest;
  private String sumr;
  //其他欠款
  private String otherArrearage;

 
  private String count;//记录个数  
  
  /**
   * 剩余期限
   */
  private String overlimited = "";
  /**
   * 月还本息
   */
  private BigDecimal corputInterest = new BigDecimal(0.000);
  /**
   * 下月还款额
   */
  private BigDecimal shouldCorputInterest = new BigDecimal(0.00);
    
  private List list=new ArrayList();  
  private List alllist=new ArrayList();  
  


  public List getAlllist() {
  return alllist;
}

public void setAlllist(List alllist) {
  this.alllist = alllist;
}

public String getBallbalance() {
  return ballbalance;
}

public void setBallbalance(String ballbalance) {
  this.ballbalance = ballbalance;
}

public String getBizdateB() {
  return bizdateB;
}

public void setBizdateB(String bizdateB) {
  this.bizdateB = bizdateB;
}

public String getBizdateE() {
  return bizdateE;
}

public void setBizdateE(String bizdateE) {
  this.bizdateE = bizdateE;
}

public String getBiztype() {
  return biztype;
}

public void setBiztype(String biztype) {
  this.biztype = biztype;
}

public Map getBiztypeMap() {
  return biztypeMap;
}

public void setBiztypeMap(Map biztypeMap) {
  this.biztypeMap = biztypeMap;
}

public String getBorrowername() {
  return borrowername;
}

public void setBorrowername(String borrowername) {
  this.borrowername = borrowername;
}

public String getCardnum() {
  return cardnum;
}

public void setCardnum(String cardnum) {
  this.cardnum = cardnum;
}

public String getContractid() {
  return contractid;
}

public void setContractid(String contractid) {
  this.contractid = contractid;
}

public String getCount() {
  return count;
}

public void setCount(String count) {
  this.count = count;
}

public String getDocnum() {
  return docnum;
}

public void setDocnum(String docnum) {
  this.docnum = docnum;
}

public List getList() {
  return list;
}

public void setList(List list) {
  this.list = list;
}

public String getLoanbank() {
  return loanbank;
}

public void setLoanbank(String loanbank) {
  this.loanbank = loanbank;
}

public String getLoankouacc() {
  return loankouacc;
}

public void setLoankouacc(String loankouacc) {
  this.loankouacc = loankouacc;
}

public String getLoanlimit() {
  return loanlimit;
}

public void setLoanlimit(String loanlimit) {
  this.loanlimit = loanlimit;
}

public String getLoanmode() {
  return loanmode;
}

public void setLoanmode(String loanmode) {
  this.loanmode = loanmode;
}

public String getLoanmoney() {
  return loanmoney;
}

public void setLoanmoney(String loanmoney) {
  this.loanmoney = loanmoney;
}

public String getNobackmoney() {
  return nobackmoney;
}

public void setNobackmoney(String nobackmoney) {
  this.nobackmoney = nobackmoney;
}

public String getOveaerloanrepay() {
  return oveaerloanrepay;
}

public void setOveaerloanrepay(String oveaerloanrepay) {
  this.oveaerloanrepay = oveaerloanrepay;
}

public String getOverplusloanmoney() {
  return overplusloanmoney;
}

public void setOverplusloanmoney(String overplusloanmoney) {
  this.overplusloanmoney = overplusloanmoney;
}

public String getOweinterest() {
  return oweinterest;
}

public void setOweinterest(String oweinterest) {
  this.oweinterest = oweinterest;
}

public String getOwepunishinterest() {
  return owepunishinterest;
}

public void setOwepunishinterest(String owepunishinterest) {
  this.owepunishinterest = owepunishinterest;
}

public String getOwercorpus() {
  return owercorpus;
}

public void setOwercorpus(String owercorpus) {
  this.owercorpus = owercorpus;
}

public String getSrealcorpus() {
  return srealcorpus;
}

public void setSrealcorpus(String srealcorpus) {
  this.srealcorpus = srealcorpus;
}

public String getSrealinterest() {
  return srealinterest;
}

public void setSrealinterest(String srealinterest) {
  this.srealinterest = srealinterest;
}

public String getSrealpunishinterest() {
  return srealpunishinterest;
}

public void setSrealpunishinterest(String srealpunishinterest) {
  this.srealpunishinterest = srealpunishinterest;
}

public String getSumr() {
  return sumr;
}

public void setSumr(String sumr) {
  this.sumr = sumr;
}

public String getTolaccordmoney() {
  return tolaccordmoney;
}

public void setTolaccordmoney(String tolaccordmoney) {
  this.tolaccordmoney = tolaccordmoney;
}

public String getTolbaddebtmoney() {
  return tolbaddebtmoney;
}

public void setTolbaddebtmoney(String tolbaddebtmoney) {
  this.tolbaddebtmoney = tolbaddebtmoney;
}

public String getTolbailmoney() {
  return tolbailmoney;
}

public void setTolbailmoney(String tolbailmoney) {
  this.tolbailmoney = tolbailmoney;
}

public String getToloverloanmoney() {
  return toloverloanmoney;
}

public void setToloverloanmoney(String toloverloanmoney) {
  this.toloverloanmoney = toloverloanmoney;
}

public String getTolrealcorpus() {
  return tolrealcorpus;
}

public void setTolrealcorpus(String tolrealcorpus) {
  this.tolrealcorpus = tolrealcorpus;
}

public String getTolrealinterest() {
  return tolrealinterest;
}

public void setTolrealinterest(String tolrealinterest) {
  this.tolrealinterest = tolrealinterest;
}

public String getTolrealpunishinterest() {
  return tolrealpunishinterest;
}

public void setTolrealpunishinterest(String tolrealpunishinterest) {
  this.tolrealpunishinterest = tolrealpunishinterest;
}

  public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

  public BigDecimal getCorputInterest() {
    return corputInterest;
  }

  public void setCorputInterest(BigDecimal corputInterest) {
    this.corputInterest = corputInterest;
  }

  public String getOverlimited() {
    return overlimited;
  }

  public void setOverlimited(String overlimited) {
    this.overlimited = overlimited;
  }

  public String getOtherArrearage() {
    return otherArrearage;
  }

  public void setOtherArrearage(String otherArrearage) {
    this.otherArrearage = otherArrearage;
  }

  public BigDecimal getShouldCorputInterest() {
    return shouldCorputInterest;
  }

  public void setShouldCorputInterest(BigDecimal shouldCorputInterest) {
    this.shouldCorputInterest = shouldCorputInterest;
  }
}