/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.querystatistics.baseinfosearch.empbaseinfo.action;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
public class EmployeeInfoListForwardACAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
//    System.out.println("经过查询职工列表信息的ActionForward");
    request.getSession().removeAttribute(EmployeeInfoListShowAC.PAGINATION_KEY);
    request.getSession().removeAttribute("infoList");
		return new ActionForward("/employeeInfoListShowAC.do");
	}
}