/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysfinance.bookmng.bookstart.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysfinance.bookmng.bookstart.bsinterface.IBookstartBS;
import org.xpup.hafmis.sysfinance.bookmng.bookstart.form.BookstartAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-20-2007
 * Copy Right Information   : 启用账套
 * Project                  : 文件名
 * @Version                 : 1.0
 * @author                  : 张列
 * 生成日期                   : 10-20-2007
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class BookstartShowAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
    try {
        //权限
        SecurityInfo securityInfo = (SecurityInfo) request.getSession()
            .getAttribute("SecurityInfo");
        //bookId
        String bookId = securityInfo.getBookId();
        
        IBookstartBS bookstartBS = (IBookstartBS) BSUtils.getBusinessService(
            "bookstartBS", this, mapping.getModuleConfig());
        
        BookstartAF bookstartAF = new BookstartAF();
        bookstartAF.setBookName(bookstartBS.getBookName(bookId));
        bookstartAF.setUseYearmonth(bookstartBS.getUserYear(bookId)+"年度"+bookstartBS.getUserMonth(bookId)+"期");
        bookstartAF.setParamValue(bookstartBS.getParamValue(bookId));
        bookstartAF.setParamExplain(bookstartBS.getParamExplain(bookId));
        request.setAttribute("bookstartAF", bookstartAF);
        
        String bookST = bookstartBS.getBookST(bookId);
        if(bookST.equals("1")){
          request.setAttribute("bookST", bookST);
        }
    } catch (Exception e) {
      e.printStackTrace();
    }
		return mapping.findForward("to_bookstart_new");
	}
}