/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysfinance.accmng.subjectdayreport.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysfinance.accmng.subjectdayreport.bsinterface.ISubjectdayreportBS;

/** 
 * MyEclipse Struts
 * Creation date: 10-26-2007
 * Copy Right Information   : 科目日报表
 * Project                  : 文件名
 * @Version                 : 1.0
 * @author                  : 张列
 * 生成日期                   : 10-26-2007
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SubjectdayreportFindACC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
    try {
      response.setContentType("text/html;charset=UTF-8");
      response.setHeader("Cache-Control", "no-cache");
      SecurityInfo securityInfo = (SecurityInfo) request.getSession()
      .getAttribute("SecurityInfo");
      ISubjectdayreportBS subjectdayreportBS = (ISubjectdayreportBS) BSUtils
      .getBusinessService("subjectdayreportBS", this, mapping
          .getModuleConfig());
      String bookId = securityInfo.getBookId();
      String subjectCode = request.getParameter("subjectCode");
      boolean temp_subjectCode = subjectdayreportBS.isSubjectCodeOneLevel(bookId, subjectCode);
      String error = "9";
      if(temp_subjectCode){
        //是一级科目
        error = "1";
      }else{
        //不是一级科目
        error = "2";
      }
      String text="displays('"+error+"')";
      response.getWriter().write(text);
      response.getWriter().close();
    } catch (Exception e) {
      e.printStackTrace();
    }
		return null;
	}
}