/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.collloanback.action;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.Pagination;
import org.xpup.hafmis.syscollection.collloanback.form.CollLoanbackTcAF;

/** 
 * MyEclipse Struts
 * Creation date: 06-25-2008
 * 
 * XDoclet definition:
 * @struts.action path="/collLoanbackTcFindAC" name="collLoanbackTcAF" scope="request" validate="true"
 */
public class CollLoanbackTcFindAC extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CollLoanbackTcAF collLoanbackTcAF = (CollLoanbackTcAF) form;// TODO Auto-generated method stub
    try {
      HashMap criterions = makeCriterionsMap(collLoanbackTcAF);
      Pagination pagination = new Pagination(0, 10, 1, " a001.id ", "DESC",criterions);
      String paginationKey = getPaginationKey();
      request.getSession().setAttribute(paginationKey, pagination);
      modifyPagination(pagination);
    } catch (Exception e) {
      // TODO: handle exception
      e.printStackTrace();
    }
		return mapping.findForward("collLoanbackTcShowAC");
	}
  
   protected String getPaginationKey() {

     return CollLoanbackTcShowAC.PAGINATION_KEY;
   }
   protected HashMap makeCriterionsMap(CollLoanbackTcAF collLoanbackTcAF) {
     HashMap m = new HashMap();
     String orgId = collLoanbackTcAF.getOrgId();
     if (orgId != null && !"".equals(orgId)) {
       m.put("orgId", orgId.trim());
     }
     String empId = collLoanbackTcAF.getEmpId();
     if (empId != null && !"".equals(empId)) {
       m.put("empId", empId.trim());
     }
     String orgName = collLoanbackTcAF.getOrgName();
     if (orgName != null && !"".equals(orgName)) {
       m.put("orgName", orgName.trim());
     }
     String empName = collLoanbackTcAF.getEmpName();
     if (empName != null && !"".equals(empName)) {
       m.put("empName", empName.trim());
     }
     String contractId = collLoanbackTcAF.getContractId();
     if (contractId != null && !"".equals(contractId)) {
       m.put("contractId", contractId.trim());
     }
     String bizDate = collLoanbackTcAF.getBizDate();
     if (bizDate != null && !"".equals(bizDate)) {
       m.put("bizDate", bizDate.trim());
     }
     
     String officeName = collLoanbackTcAF.getOfficeName();
     m.put("officeName", officeName);
     
     String bankName = collLoanbackTcAF.getBankName();
     m.put("bankName", bankName);
     
     return m;
   }
 protected void modifyPagination(Pagination pagination) {
 }
}