/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.syscollection.collloanback.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.common.util.Pagination;
import org.xpup.common.util.PaginationUtils;
import org.xpup.hafmis.orgstrct.dto.OfficeDto;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.syscollection.collloanback.bsinterface.ICollLoanbackBS;
import org.xpup.hafmis.syscollection.collloanback.form.CollLoanbackTcAF;
import org.xpup.security.common.domain.Userslogincollbank;

/** 
 * MyEclipse Struts
 * Creation date: 06-25-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CollLoanbackTcShowAC extends Action {
	/*
	 * Generated Methods
	 */
  public static final String PAGINATION_KEY = "org.xpup.hafmis.syscollection.collloanback.action.CollLoanbackTcShowAC";
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
    try {
      SecurityInfo securityInfo = (SecurityInfo) request.getSession()
      .getAttribute("SecurityInfo");
      List officeList = securityInfo.getOfficeList();
      List officeList1 = new ArrayList();
      OfficeDto officedto = null;
      Iterator itr1 = officeList.iterator();
      while (itr1.hasNext()) {
        officedto = (OfficeDto) itr1.next();
        officeList1.add(new org.apache.struts.util.LabelValueBean(officedto.getOfficeName(), officedto.getOfficeCode()));
      }
      List loanbankList1 = null;
        // 取出用户权限放款银行,显示在下拉菜单中
      List loanbankList = securityInfo.getCollBankList();
      loanbankList1 = new ArrayList();
      Userslogincollbank bank = null;
      Iterator itr2 = loanbankList.iterator();
      while (itr2.hasNext()) {
        bank = (Userslogincollbank) itr2.next();
        loanbankList1.add(new org.apache.struts.util.LabelValueBean(bank
              .getCollBankName(), bank.getCollBankId().toString()));
        }
      
      String paginationKey = getPaginationKey();
      Pagination pagination = getPagination(paginationKey, request);
      PaginationUtils.updatePagination(pagination, request);
      
      ICollLoanbackBS collLoanbackBS = (ICollLoanbackBS) BSUtils
       .getBusinessService("collLoanbackBS", this, mapping.getModuleConfig());
      List list = new ArrayList();
      List listcount = new ArrayList();
      list = collLoanbackBS.findCollLoanbackTcList(pagination);
      listcount = collLoanbackBS.findCollLoanbackTcCount(pagination);
      
      CollLoanbackTcAF collLoanbackTcAF = new CollLoanbackTcAF();
      collLoanbackTcAF.setList(list);
      collLoanbackTcAF.setPersonSum(listcount.size());
      collLoanbackTcAF.setCheckMoneySum(collLoanbackBS.getCollLoanbackCheckMoney(listcount));
      
      request.setAttribute("collLoanbackTcAF", collLoanbackTcAF);
      request.setAttribute("officeList1", officeList1);
      request.setAttribute("loanbankList1", loanbankList1);
      request.getSession().setAttribute(CollLoanbackTcShowAC.PAGINATION_KEY, pagination);
    } catch (Exception e) {
      e.printStackTrace();
    }
		return mapping.findForward("to_collloanbacktc_show");
	}
  
  private Pagination getPagination(String paginationKey,
      HttpServletRequest request) {
    Pagination pagination = (Pagination) request.getSession().getAttribute(
        paginationKey);
    if (pagination == null) {
      pagination = new Pagination(0, 10, 1, "a001.id", "DESC", new HashMap(
          0));
      request.getSession().setAttribute(paginationKey, pagination);
    }
    return pagination;
  }

  protected String getPaginationKey() {
    return PAGINATION_KEY;
  }
}