/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.xpup.hafmis.sysfinance.bookmng.settlemodle.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.xpup.common.util.BSUtils;
import org.xpup.common.util.Pagination;
import org.xpup.common.util.PaginationUtils;
import org.xpup.hafmis.orgstrct.dto.SecurityInfo;
import org.xpup.hafmis.sysfinance.bookmng.settlemodle.bsinterface.ISettlemodleBS;
import org.xpup.hafmis.sysfinance.bookmng.settlemodle.form.SettlemodleNewAF;

/** 
 * MyEclipse Struts
 * Creation date: 10-24-2007
 * Copy Right Information   : 结算方式
 * Project                  : 文件名
 * @Version                 : 1.0
 * @author                  : 张列
 * 生成日期                   : 10-24-2007
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SettlemodleShowAC extends Action {
	/*
	 * Generated Methods
	 */

  public static final String PAGINATION_KEY = "org.xpup.hafmis.sysfinance.bookmng.settlemodle.action.SettlemodleShowAC";
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
    try {
      Pagination pagination = getPagination(PAGINATION_KEY, request);
      SettlemodleNewAF settlemodleNewAF = new SettlemodleNewAF();
      List list = new ArrayList();
      PaginationUtils.updatePagination(pagination, request);
      //权限
      SecurityInfo securityInfo = (SecurityInfo) request.getSession()
          .getAttribute("SecurityInfo");
      //bookId
      String bookId = securityInfo.getBookId();
      ISettlemodleBS settlemodleBS = (ISettlemodleBS) BSUtils.getBusinessService(
          "settlemodleBS", this, mapping.getModuleConfig());
      
      list = settlemodleBS.findSettlemodleList(pagination, bookId);
      int count = settlemodleBS.querySettlemodleCount(bookId);
      if(list.size() == 0){
        request.setAttribute("noData", "0");
      }
      pagination.setNrOfElements(count);
      //修改
      if(request.getAttribute("updateInfo") != null){
        String paraId = (String)request.getAttribute("paraId");
        String paramExplain = (String)request.getAttribute("paramExplain");
        settlemodleNewAF.setParaId(paraId);
        settlemodleNewAF.setParamExplain(paramExplain);
        request.setAttribute("updateInfo", "updateInfo");
      }
      settlemodleNewAF.setList(list);
      request.setAttribute("settlemodleNewAF", settlemodleNewAF);
    } catch (Exception e) {
      e.printStackTrace();
    }
		return mapping.findForward("to_settlemodle_show");
	}
  
  private Pagination getPagination(String paginationKey,
      HttpServletRequest request) {
    Pagination pagination = (Pagination) request.getSession().getAttribute(
        paginationKey);
    if (pagination == null) {
      pagination = new Pagination(0, 10, 1, "f102.para_id", "DESC", new HashMap(0));
      request.getSession().setAttribute(paginationKey, pagination);
    }
    return pagination;
  }
}